vendor_id: 0x00002838
product_id: 0x00009251

rpdo:
  - index: 0x1600
    channels:
      - { index: 0x2066, subindex: 0x01, type: uint8, name: "y_ctrl1" }
      - { index: 0x2066, subindex: 0x02, type: uint8, name: "y_ctrl2" }
      - { index: 0x2066, subindex: 0x03, type: uint16, name: "y_ctrl3" }
      - { index: 0x2066, subindex: 0x04, type: int32, name: "y_ctrl4" }
      - { index: 0x2066, subindex: 0x05, type: int32, name: "y_ctrl5" }
      - { index: 0x2066, subindex: 0x06, type: int32, name: "y_ctrl6" }
      - { index: 0x20ca, subindex: 0x01, type: uint8, name: "x_ctrl1" }
      - { index: 0x20ca, subindex: 0x02, type: uint8, name: "x_ctrl2" }
      - { index: 0x20ca, subindex: 0x03, type: uint16, name: "x_ctrl3" }
      - { index: 0x20ca, subindex: 0x04, type: int32, name: "x_ctrl4" }
      - { index: 0x20ca, subindex: 0x05, type: int32, name: "x_ctrl5" }
      - { index: 0x20ca, subindex: 0x06, type: int32, name: "x_ctrl6" }

tpdo:
  - index: 0x1a00
    channels:
      - { index: 0x2065, subindex: 0x01, type: uint8, name: "y_status1" }
      - { index: 0x2065, subindex: 0x02, type: uint8, name: "y_status2" }
      - { index: 0x2065, subindex: 0x03, type: int32, name: "y_torque" }
      - { index: 0x2065, subindex: 0x04, type: uint8, name: "y_live_counter" }
      - { index: 0x2065, subindex: 0x05, type: uint8, name: "y_array_counter" }
      - { index: 0x20c9, subindex: 0x01, type: uint8, name: "x_status1" }
      - { index: 0x20c9, subindex: 0x02, type: uint8, name: "x_status2" }
      - { index: 0x20c9, subindex: 0x03, type: int32, name: "x_torque" }
      - { index: 0x20c9, subindex: 0x04, type: uint8, name: "x_live_counter" }
      - { index: 0x20c9, subindex: 0x05, type: uint8, name: "x_array_counter" }

sm:
  - { index: 2, type: output, pdo: rpdo, watchdog: enable }
  - { index: 3, type: input,  pdo: tpdo, watchdog: disable }