vendor_id: 0x00002838
product_id: 0x00009251

rpdo:
  - index: 0x1600
    channels:
      - { index: 0x2066, subindex: 0x01, type: uint8, name: "ctrl1" }
      - { index: 0x2066, subindex: 0x02, type: uint8, name: "ctrl2" }
      - { index: 0x2066, subindex: 0x03, type: uint16, name: "ctrl3" }
      - { index: 0x2066, subindex: 0x04, type: int32, name: "ctrl4" }
      - { index: 0x2066, subindex: 0x05, type: int32, name: "ctrl5" }
      - { index: 0x2066, subindex: 0x06, type: int32, name: "ctrl6" }

tpdo:
  - index: 0x1a00
    channels:
      - { index: 0x2065, subindex: 0x01, type: uint8, name: "status1" }
      - { index: 0x2065, subindex: 0x02, type: uint8, name: "status2" }
      - { index: 0x2065, subindex: 0x03, type: int32, name: "torque" }
      - { index: 0x2065, subindex: 0x04, type: uint8, name: "live_counter" }
      - { index: 0x2065, subindex: 0x05, type: uint8, name: "array_counter" }

sm:
  - { index: 2, type: output, pdo: rpdo, watchdog: enable }
  - { index: 3, type: input,  pdo: tpdo, watchdog: disable }