controller_manager:
  ros__parameters:
    update_rate: 1000 # Hz

    forward_velocity_controller:
      type: velocity_controllers/JointGroupVelocityController

    forward_position_controller:
      type: position_controllers/JointGroupPositionController

    forward_command_controller:
      type: forward_command_controller/ForwardCommandController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    joint_trajectory_controller:
      type: "joint_trajectory_controller/JointTrajectoryController"

    scaled_trajectory_controller:
      type: "scaled_fjt_controller/ScaledFjtController"

    state_controller:
      type: ethercat_controllers/CiA402Controller


forward_velocity_controller:
  ros__parameters:
    joints:
    - joint_1
    - joint_2
    - joint_3
    command_interface:
    - velocity

forward_position_controller:
  ros__parameters:
    joints:
    - joint_1
    - joint_2
    - joint_3
    command_interface:
    - position

forward_command_controller:
  ros__parameters:
    joints:
    - joint_1
    - joint_2
    - joint_3
    interface_name: position

state_controller:
  ros__parameters:
    dofs:
      - joint_1
      - joint_2
      - joint_3

joint_trajectory_controller:
  ros__parameters:
    joints:
    - joint_1
    - joint_2
    - joint_3

    command_interfaces:
    - position

    state_interfaces:
    - position
    - velocity

scaled_trajectory_controller:
  ros__parameters:
    joints:
    - joint_1
    - joint_2
    - joint_3
    command_interfaces:
    - position
    state_interfaces:
    - position
    - velocity
    open_loop_control: true
    constraints:
      goal_time: 0.0
  # action_monitor_rate: 20.0
  # allow_partial_joints_goal: true
  # open_loop_control: false
  # constraints:
  #   stopped_velocity_tolerance: 0.01
  #   goal_time: 0.0
  #   joint_0:
  #     trajectory: 0.05
  #     goal: 0.03
  #   joint_1:
  #     trajectory: 0.05
  #     goal: 0.03
  # gains:
  #   joint_1:
  #     p: 2.0
  #     i: 0.0
  #     d: 0.0
  #     i_clamp: 30000.0
  #     ff_velocity_scale: 0.1
  #   joint_2:
  #     p: 2.0
  #     i: 0.0
  #     d: 0.0
  #     i_clamp: 30000.0
  #     ff_velocity_scale: 0.1
  #   joint_3:
  #     p: 2.0
  #     i: 0.0
  #     d: 0.0
  #     i_clamp: 30000.0
  #     ff_velocity_scale: 0.1
