# Configuration file for Maxon EPOS3 drive
vendor_id: 0x000001dd
product_id: 0x10305070
assign_activate: 0x0300  # DC Synch register
auto_fault_reset: false  # true = automatic fault reset, false = fault reset on rising edge command interface "reset_fault"

sdo:  # sdo data to be transferred at drive startup
  - {index: 0x6098, sub_index: 0, type: int8, value: 35} # Set interpolation time for cyclic modes to 10 ms
#sdo:  # sdo data to be transferred at drive startup
#  - {index: 0x60C2, sub_index: 1, type: int8, value: 10} # Set interpolation time for cyclic modes to 10 ms
#  - {index: 0x60C2, sub_index: 2, type: int8, value: -3} # Set base 10-3s
rpdo:  # RxPDO = receive PDO Mapping
  - index: 0x1601
    channels:
      - {index: 0x6040, sub_index: 0, type: uint16, command_interface: control_word, default: 0}  # Control word
      - {index: 0x607a, sub_index: 0, type: int32, command_interface: position, default: .nan, factor: 84026415.09}  # Target position #12109973.47
      - {index: 0x60ff, sub_index: 0, type: int32, command_interface: velocity, default: 0, factor: 39374.5}  # Target velocity
      # - {index: 0x6071, sub_index: 0, type: int16, default: 0}  # Target torque
      - {index: 0x6060, sub_index: 0, type: int8, command_interface: mode_of_operation} # , default: 8}  # Mode of operation
      # - {index: 0x60b0, sub_index: 0, type: int32, default: 0}  # Offset position
      - {index: 0x60b1, sub_index: 0, type: int32, command_interface: offset_velocity, factor: 39374.5, default: 0}  # Offset velocity
      # - {index: 0x60b2, sub_index: 0, type: int16, default: 0}  # Offset torque
      # - {index: 0x2078, sub_index: 1, type: uint16, default: 0}  # Digital Output Functionalities
      # - {index: 0x60b8, sub_index: 0, type: uint16, default: 0}  # Touch Probe Function
tpdo:  # TxPDO = transmit PDO Mapping
  - index: 0x1a01
    channels:
      - {index: 0x6041, sub_index: 0, type: uint16, state_interface: status_word}  # Status word
      - {index: 0x6064, sub_index: 0, type: int32, state_interface: position, factor: 0.00000001189742}  # Position actual value  #0.000000083
      - {index: 0x606c, sub_index: 0, type: int32, state_interface: velocity, factor: 0.00002539}  # Velocity actual value 
      # - {index: 0x6077, sub_index: 0, type: int16, state_interface: effort}  # Torque actual value
      - {index: 0x6061, sub_index: 0, type: int8, state_interface: mode_of_operation}  # Mode of operation display
      # - {index: 0x2071, sub_index: 1, type: int16}  # Digital Input Functionalities State
      # - {index: 0x60b9, sub_index: 0, type: int16}  # Touch Probe Status
      # - {index: 0x60ba, sub_index: 0, type: int32}  # Touch Probe Position 1 Positive Value
      # - {index: 0x60bb, sub_index: 0, type: int32}  # Touch Probe Position 1 Negative Value