# Configuration file for Beckhoff EL2008
 vendor_id: 0x00000002
 product_id: 0x03ea3052
 tdpo:  # TxPDO
   - index: 0x1a00
     channels:
       - {index: 0x6000, sub_index: 1, type: bool, mask: 1, state_interface: d_input.1}
   - index: 0x1a01
     channels:
       - {index: 0x6010, sub_index: 1, type: bool, mask: 2, state_interface: d_input.2}
   
 sm:  # Sync Manager
   - {index: 0, type: input, pdo: tpdo, watchdog: enable}