plc_controller_manager:
  ros__parameters:
    update_rate: 500 #Hz
    PLC_controller:
      type: plc_controller/PLCController
PLC_controller:
  ros__parameters:
    gpios:
      - PLC_node
    command_interfaces:
      PLC_node:
        - interfaces:
          - mode_of_operation
          - power_cutoff
          - sonar_teach
          - s_output.4
          - estop
          - manual_mode
          - force_sensors_pwr
          - brake_disable
    state_interfaces:
      PLC_node:
        - interfaces:
          - s_input.0        
          - estop
          - reset
          - manual_switch_pressed
          - s_input.5
          - s_input.6
          - s_input.7
          - s_input.8
