controller_manager:
  ros__parameters:
    update_rate: 250  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    #scaled_trajectory_controller:
    #  type: scaled_fjt_controller/ScaledFjtController
      
    state_controller:
      type: ethercat_controllers/CiA402Controller

    ft_sensor_command_broadcaster:
      type: force_torque_sensor_broadcaster/ForceTorqueSensorBroadcaster

    admittance_controller:
        type: "cnr_admittance_controller/AdmittanceController"

    forward_position_controller:
      type: position_controllers/JointGroupPositionController

    forward_velocity_controller:
      type: velocity_controllers/JointGroupVelocityController

    remapping_controller:
      type: "remapping_controller/RemappingController"

ft_sensor_command_broadcaster:
  ros__parameters:
    frame_id: "ee_link"
    interface_names:
      force:
        x: "ft_sensor/force.x"
        y: "ft_sensor/force.y"
        z: "ft_sensor/force.z"
      torque:
        x: "ft_sensor/torque.x"
        y: "ft_sensor/torque.y"
        z: "ft_sensor/torque.z"
    # offset:
    #   force:
    #     x: 249.12
    #     y: -15.15
    #     z: 18.6
    #   torque:
    #     x: 0.12
    #     y: -0.7
    #     z: 2.12  

forward_position_controller:
  ros__parameters:
    joints:
      - joint_yaw

forward_velocity_controller:
  ros__parameters:
    joints:
      - joint_x
      - joint_y
      - joint_z

joint_trajectory_controller:
  ros__parameters:
    joints:
      - joint_z
      - joint_y
      - joint_x

    command_interfaces:
      - position
      - velocity

    state_interfaces:
      - position
      - velocity

    command_joints:
      - remapping_controller/joint_z
      - remapping_controller/joint_y
      - remapping_controller/joint_x

    speed_scaling:
      initial_scaling_factor: 1.0
      filter_coefficient: 0.9
      policy: "MINIMUM"
      subscribed_topics: 
        - "~/speed_scaling_input"


# scaled_trajectory_controller:
#   ros__parameters:
#     joints:
#     - joint_x
#     - joint_y
#     - joint_z
#     speed_scaling:
#       initial_scaling_factor: 1.0
#       filter_coefficient: 0.9
#       policy: "MINIMUM"
#       subscribed_topics: 
#         - "~/speed_scaling_input"

#     command_interfaces:
#     - position
#     - velocity
#     state_interfaces:
#     - position
#     - velocity
#     open_loop_control: true
#     constraints:
#       goal_time: 0.0
#     spline_order: 2

state_controller:
  ros__parameters:
    dofs:
      - joint_x
      - joint_y
      - joint_z

admittance_controller:
  ros__parameters:
    joints:
    - joint_y
    - joint_x
    - joint_z
    - joint_yaw
    command_interfaces:
    - velocity
    state_interfaces:
    - position
    - velocity
    kinematics:
      plugin_name: kinematics_interface_kdl/KinematicsInterfaceKDL
      plugin_package: kinematics_interface
      base: base_link # Assumed to be stationary
      tip: ft_link
      group_name: fmrrehab
      alpha: 0.0005
    admittance:
      mass: [ 10.0, 100.0, 10.0, 0.1, 0.1, 0.1 ]
      stiffness: [ 0.0, 0.0, 0.0, 500.0, 500.0, 500.0 ] #N/m
      damping_ratio: [ 2.828427, 2.828427, 2.828427, 2.828427, 2.828427, 2.828427 ]
      joint_damping: [10.0, 5.0, 5.0, 0.0]
      selected_axes: [ true, true, true, false, false, false ]
    ft_sensor:
      name: "ft_sensor"
      frame:
        id: "ft_link"
      low_pass_filter_frequency: 20.0
      force_deadband: 5.0
      torque_deadband: 2.0
    control:
      frame:
        id: "base_link"
        external: false
    fixed_world_frame:
      frame:
        id: "base_link"
        external: false
    gravity_compensation:
      frame:
        id: "ft_link"
        external: false
      CoG:
        pos: [ 0.01, 0.01, 0.01 ]
        force: 0.01

remapping_controller:
  ros__parameters:
    joints: 
      - joint_x
      - joint_y
      - joint_z
    input_command_interfaces: 
      - position
      - velocity
    output_command_interfaces: 
      - position
      - offset_velocity
