# Sick GetC100
# This file is part of the Fit4Med project.
vendor_id: 0x01000056
product_id: 0x00002302
rpdo:  # RxPDO
  - index: 0x1600
    channels:
    - {index: 0x2001, sub_index: 1, type: uint8, command_interface: s_output.1}
    - {index: 0x2001, sub_index: 2, type: uint8, command_interface: s_output.2}
    - {index: 0x2001, sub_index: 3, type: uint8, command_interface: s_output.3}
    - {index: 0x2001, sub_index: 4, type: uint8, command_interface: s_output.4}
    - {index: 0x2001, sub_index: 5, type: uint8, command_interface: s_output.5}
    - {index: 0x2001, sub_index: 6, type: uint8, command_interface: s_output.6}
    - {index: 0x2001, sub_index: 7, type: uint8, command_interface: s_output.7}
    - {index: 0x2001, sub_index: 8, type: uint8, command_interface: s_output.8}
    - {index: 0x2001, sub_index: 9, type: uint8, command_interface: s_output.9}
    - {index: 0x2001, sub_index: 10, type: uint8, command_interface: s_output.10}
tpdo:  # TxPDO
  - index: 0x1a00
    channels:
    - {index: 0x10f3, sub_index: 4, type: bit1, state_interface: s_msg, default: 0}
  - index: 0x1a01
    channels:
    - {index: 0x2000, sub_index: 1, type: uint8, state_interface: s_input.1}
    - {index: 0x2000, sub_index: 2, type: uint8, state_interface: s_input.2}
    - {index: 0x2000, sub_index: 3, type: uint8, state_interface: s_input.3}
    - {index: 0x2000, sub_index: 4, type: uint8, state_interface: s_input.4}
    - {index: 0x2000, sub_index: 5, type: uint8, state_interface: s_input.5}
    - {index: 0x2000, sub_index: 6, type: uint8, state_interface: s_input.6}
    - {index: 0x2000, sub_index: 7, type: uint8, state_interface: s_input.7}
    - {index: 0x2000, sub_index: 8, type: uint8, state_interface: s_input.8}
    - {index: 0x2000, sub_index: 9, type: uint8, state_interface: s_input.9}
    - {index: 0x2000, sub_index: 10, type: uint8, state_interface: s_input.10}
sm:  # Sync Manager
  - {index: 2, type: output, pdo: rpdo, watchdog: enable}
  - {index: 3, type: input, pdo: tpdo, watchdog: enable}