# Sick GetC100
# This file is part of the Fit4Med project.
vendor_id: 0x01000056
product_id: 0x00002302
rpdo:  # RxPDO
  - index: 0x1600
    channels:
    - {index: 0x2001, sub_index: 1, type: bit80, command_interface: s_output.1}
tpdo:  # TxPDO
  - index: 0x1a00
    channels:
    - {index: 0x10f3, sub_index: 4, type: bit1, state_interface: s_msg, default: 0}
  - index: 0x1a01
    channels:
    - {index: 0x2000, sub_index: 1, type: bit80, state_interface: s_input.1, default: 0}
sm:  # Sync Manager
  - {index: 2, type: output, pdo: rpdo, watchdog: enable}
  - {index: 3, type: input, pdo: tpdo, watchdog: enable}