cart_coordinates:
  - [0.0, 0.0, 0.0]
  - [0.3, 0.3, 0.2]
  - [0.3, 0.3, 0.0]
  - [0.0, 0.0, 0.0] #Always end with home position (0,0,0)

velocities:
  - [0.0, 0.0, 0.0]
  - [0.0, 0.0, 0.0]
  - [0.0, 0.0, 0.0]
  - [0.0, 0.0, 0.0]

accelerations:
  - [0.0, 0.0, 0.0]
  - [0.0, 0.0, 0.0]
  - [0.0, 0.0, 0.0]
  - [0.0, 0.0, 0.0]

durations:
  - 0.0
  - 5.0
  - 7.0
  - 10.0