# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\FMRRMainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_FMRRMainWindow(object):
    def setupUi(self, FMRRMainWindow):
        FMRRMainWindow.setObjectName("FMRRMainWindow")
        FMRRMainWindow.resize(1469, 933)
        font = QtGui.QFont()
        font.setPointSize(9)
        FMRRMainWindow.setFont(font)
        self.spinBoxPercPhase02 = QtWidgets.QSpinBox(FMRRMainWindow)
        self.spinBoxPercPhase02.setGeometry(QtCore.QRect(195, 230, 55, 27))
        self.spinBoxPercPhase02.setMaximum(100)
        self.spinBoxPercPhase02.setObjectName("spinBoxPercPhase02")
        self.spinBoxPercPhase10 = QtWidgets.QSpinBox(FMRRMainWindow)
        self.spinBoxPercPhase10.setGeometry(QtCore.QRect(195, 470, 55, 27))
        self.spinBoxPercPhase10.setMaximum(100)
        self.spinBoxPercPhase10.setObjectName("spinBoxPercPhase10")
        self.progressBarPhase04 = QtWidgets.QProgressBar(FMRRMainWindow)
        self.progressBarPhase04.setGeometry(QtCore.QRect(73, 290, 118, 23))
        self.progressBarPhase04.setProperty("value", 24)
        self.progressBarPhase04.setObjectName("progressBarPhase04")
        self.spinBoxPercPhase05 = QtWidgets.QSpinBox(FMRRMainWindow)
        self.spinBoxPercPhase05.setGeometry(QtCore.QRect(195, 320, 55, 27))
        self.spinBoxPercPhase05.setMaximum(100)
        self.spinBoxPercPhase05.setObjectName("spinBoxPercPhase05")
        self.progressBarPhase05 = QtWidgets.QProgressBar(FMRRMainWindow)
        self.progressBarPhase05.setGeometry(QtCore.QRect(73, 320, 118, 23))
        self.progressBarPhase05.setProperty("value", 24)
        self.progressBarPhase05.setObjectName("progressBarPhase05")
        self.progressBarPhase13 = QtWidgets.QProgressBar(FMRRMainWindow)
        self.progressBarPhase13.setGeometry(QtCore.QRect(385, 260, 118, 23))
        self.progressBarPhase13.setProperty("value", 24)
        self.progressBarPhase13.setObjectName("progressBarPhase13")
        self.progressBarPhase11 = QtWidgets.QProgressBar(FMRRMainWindow)
        self.progressBarPhase11.setGeometry(QtCore.QRect(385, 200, 118, 23))
        self.progressBarPhase11.setProperty("value", 24)
        self.progressBarPhase11.setObjectName("progressBarPhase11")
        self.progressBarPhase15 = QtWidgets.QProgressBar(FMRRMainWindow)
        self.progressBarPhase15.setGeometry(QtCore.QRect(385, 320, 118, 23))
        self.progressBarPhase15.setProperty("value", 24)
        self.progressBarPhase15.setObjectName("progressBarPhase15")
        self.spinBoxPercPhase07 = QtWidgets.QSpinBox(FMRRMainWindow)
        self.spinBoxPercPhase07.setGeometry(QtCore.QRect(195, 380, 55, 27))
        self.spinBoxPercPhase07.setMaximum(100)
        self.spinBoxPercPhase07.setObjectName("spinBoxPercPhase07")
        self.progressBarPhase02 = QtWidgets.QProgressBar(FMRRMainWindow)
        self.progressBarPhase02.setGeometry(QtCore.QRect(73, 230, 118, 23))
        self.progressBarPhase02.setProperty("value", 24)
        self.progressBarPhase02.setObjectName("progressBarPhase02")
        self.spinBoxPercPhase08 = QtWidgets.QSpinBox(FMRRMainWindow)
        self.spinBoxPercPhase08.setGeometry(QtCore.QRect(195, 410, 55, 27))
        self.spinBoxPercPhase08.setMaximum(100)
        self.spinBoxPercPhase08.setObjectName("spinBoxPercPhase08")
        self.progressBarPhase20 = QtWidgets.QProgressBar(FMRRMainWindow)
        self.progressBarPhase20.setGeometry(QtCore.QRect(385, 470, 118, 23))
        self.progressBarPhase20.setProperty("value", 24)
        self.progressBarPhase20.setObjectName("progressBarPhase20")
        self.spinBoxPercPhase15 = QtWidgets.QSpinBox(FMRRMainWindow)
        self.spinBoxPercPhase15.setGeometry(QtCore.QRect(515, 320, 55, 27))
        self.spinBoxPercPhase15.setMaximum(100)
        self.spinBoxPercPhase15.setObjectName("spinBoxPercPhase15")
        self.progressBarPhase19 = QtWidgets.QProgressBar(FMRRMainWindow)
        self.progressBarPhase19.setGeometry(QtCore.QRect(385, 440, 118, 23))
        self.progressBarPhase19.setProperty("value", 24)
        self.progressBarPhase19.setObjectName("progressBarPhase19")
        self.spinBoxPercPhase09 = QtWidgets.QSpinBox(FMRRMainWindow)
        self.spinBoxPercPhase09.setGeometry(QtCore.QRect(195, 440, 55, 27))
        self.spinBoxPercPhase09.setMaximum(100)
        self.spinBoxPercPhase09.setObjectName("spinBoxPercPhase09")
        self.progressBarPhase08 = QtWidgets.QProgressBar(FMRRMainWindow)
        self.progressBarPhase08.setGeometry(QtCore.QRect(73, 410, 118, 23))
        self.progressBarPhase08.setProperty("value", 24)
        self.progressBarPhase08.setObjectName("progressBarPhase08")
        self.spinBoxPercPhase04 = QtWidgets.QSpinBox(FMRRMainWindow)
        self.spinBoxPercPhase04.setGeometry(QtCore.QRect(195, 290, 55, 27))
        self.spinBoxPercPhase04.setMaximum(100)
        self.spinBoxPercPhase04.setObjectName("spinBoxPercPhase04")
        self.progressBarPhase16 = QtWidgets.QProgressBar(FMRRMainWindow)
        self.progressBarPhase16.setGeometry(QtCore.QRect(385, 350, 118, 23))
        self.progressBarPhase16.setProperty("value", 24)
        self.progressBarPhase16.setObjectName("progressBarPhase16")
        self.progressBarPhase01 = QtWidgets.QProgressBar(FMRRMainWindow)
        self.progressBarPhase01.setGeometry(QtCore.QRect(73, 200, 118, 23))
        self.progressBarPhase01.setProperty("value", 24)
        self.progressBarPhase01.setObjectName("progressBarPhase01")
        self.spinBoxPercPhase11 = QtWidgets.QSpinBox(FMRRMainWindow)
        self.spinBoxPercPhase11.setGeometry(QtCore.QRect(515, 200, 55, 27))
        self.spinBoxPercPhase11.setMaximum(100)
        self.spinBoxPercPhase11.setObjectName("spinBoxPercPhase11")
        self.progressBarPhase17 = QtWidgets.QProgressBar(FMRRMainWindow)
        self.progressBarPhase17.setGeometry(QtCore.QRect(385, 380, 118, 23))
        self.progressBarPhase17.setProperty("value", 24)
        self.progressBarPhase17.setObjectName("progressBarPhase17")
        self.spinBoxPercPhase03 = QtWidgets.QSpinBox(FMRRMainWindow)
        self.spinBoxPercPhase03.setGeometry(QtCore.QRect(195, 260, 55, 27))
        self.spinBoxPercPhase03.setMaximum(100)
        self.spinBoxPercPhase03.setObjectName("spinBoxPercPhase03")
        self.progressBarPhase12 = QtWidgets.QProgressBar(FMRRMainWindow)
        self.progressBarPhase12.setGeometry(QtCore.QRect(385, 230, 118, 23))
        self.progressBarPhase12.setProperty("value", 24)
        self.progressBarPhase12.setObjectName("progressBarPhase12")
        self.progressBarPhase06 = QtWidgets.QProgressBar(FMRRMainWindow)
        self.progressBarPhase06.setGeometry(QtCore.QRect(73, 350, 118, 23))
        self.progressBarPhase06.setProperty("value", 24)
        self.progressBarPhase06.setObjectName("progressBarPhase06")
        self.spinBoxPercPhase01 = QtWidgets.QSpinBox(FMRRMainWindow)
        self.spinBoxPercPhase01.setGeometry(QtCore.QRect(195, 200, 55, 27))
        self.spinBoxPercPhase01.setMaximum(100)
        self.spinBoxPercPhase01.setObjectName("spinBoxPercPhase01")
        self.spinBoxPercPhase06 = QtWidgets.QSpinBox(FMRRMainWindow)
        self.spinBoxPercPhase06.setGeometry(QtCore.QRect(195, 350, 55, 27))
        self.spinBoxPercPhase06.setMaximum(100)
        self.spinBoxPercPhase06.setObjectName("spinBoxPercPhase06")
        self.spinBoxPercPhase13 = QtWidgets.QSpinBox(FMRRMainWindow)
        self.spinBoxPercPhase13.setGeometry(QtCore.QRect(515, 260, 55, 27))
        self.spinBoxPercPhase13.setMaximum(100)
        self.spinBoxPercPhase13.setObjectName("spinBoxPercPhase13")
        self.spinBoxPercPhase16 = QtWidgets.QSpinBox(FMRRMainWindow)
        self.spinBoxPercPhase16.setGeometry(QtCore.QRect(515, 350, 55, 27))
        self.spinBoxPercPhase16.setMaximum(100)
        self.spinBoxPercPhase16.setObjectName("spinBoxPercPhase16")
        self.progressBarPhase03 = QtWidgets.QProgressBar(FMRRMainWindow)
        self.progressBarPhase03.setGeometry(QtCore.QRect(73, 260, 118, 23))
        self.progressBarPhase03.setProperty("value", 24)
        self.progressBarPhase03.setObjectName("progressBarPhase03")
        self.progressBarPhase14 = QtWidgets.QProgressBar(FMRRMainWindow)
        self.progressBarPhase14.setGeometry(QtCore.QRect(385, 290, 118, 23))
        self.progressBarPhase14.setProperty("value", 24)
        self.progressBarPhase14.setObjectName("progressBarPhase14")
        self.spinBoxPercPhase12 = QtWidgets.QSpinBox(FMRRMainWindow)
        self.spinBoxPercPhase12.setGeometry(QtCore.QRect(515, 230, 55, 27))
        self.spinBoxPercPhase12.setMaximum(100)
        self.spinBoxPercPhase12.setObjectName("spinBoxPercPhase12")
        self.spinBoxPercPhase14 = QtWidgets.QSpinBox(FMRRMainWindow)
        self.spinBoxPercPhase14.setGeometry(QtCore.QRect(515, 290, 55, 27))
        self.spinBoxPercPhase14.setMaximum(100)
        self.spinBoxPercPhase14.setObjectName("spinBoxPercPhase14")
        self.progressBarPhase07 = QtWidgets.QProgressBar(FMRRMainWindow)
        self.progressBarPhase07.setGeometry(QtCore.QRect(73, 380, 118, 23))
        self.progressBarPhase07.setProperty("value", 24)
        self.progressBarPhase07.setObjectName("progressBarPhase07")
        self.spinBoxPercPhase19 = QtWidgets.QSpinBox(FMRRMainWindow)
        self.spinBoxPercPhase19.setGeometry(QtCore.QRect(515, 440, 55, 27))
        self.spinBoxPercPhase19.setMaximum(100)
        self.spinBoxPercPhase19.setObjectName("spinBoxPercPhase19")
        self.progressBarPhase10 = QtWidgets.QProgressBar(FMRRMainWindow)
        self.progressBarPhase10.setGeometry(QtCore.QRect(73, 470, 118, 23))
        self.progressBarPhase10.setProperty("value", 24)
        self.progressBarPhase10.setObjectName("progressBarPhase10")
        self.spinBoxPercPhase17 = QtWidgets.QSpinBox(FMRRMainWindow)
        self.spinBoxPercPhase17.setGeometry(QtCore.QRect(515, 380, 55, 27))
        self.spinBoxPercPhase17.setMaximum(100)
        self.spinBoxPercPhase17.setObjectName("spinBoxPercPhase17")
        self.spinBoxPercPhase18 = QtWidgets.QSpinBox(FMRRMainWindow)
        self.spinBoxPercPhase18.setGeometry(QtCore.QRect(515, 410, 55, 27))
        self.spinBoxPercPhase18.setMaximum(100)
        self.spinBoxPercPhase18.setObjectName("spinBoxPercPhase18")
        self.progressBarPhase18 = QtWidgets.QProgressBar(FMRRMainWindow)
        self.progressBarPhase18.setGeometry(QtCore.QRect(385, 410, 118, 23))
        self.progressBarPhase18.setProperty("value", 24)
        self.progressBarPhase18.setObjectName("progressBarPhase18")
        self.progressBarPhase09 = QtWidgets.QProgressBar(FMRRMainWindow)
        self.progressBarPhase09.setGeometry(QtCore.QRect(73, 440, 118, 23))
        self.progressBarPhase09.setProperty("value", 24)
        self.progressBarPhase09.setObjectName("progressBarPhase09")
        self.spinBoxPercPhase20 = QtWidgets.QSpinBox(FMRRMainWindow)
        self.spinBoxPercPhase20.setGeometry(QtCore.QRect(515, 470, 55, 27))
        self.spinBoxPercPhase20.setMaximum(100)
        self.spinBoxPercPhase20.setObjectName("spinBoxPercPhase20")
        self.lineEdit_RehabilitationProtocol = QtWidgets.QLineEdit(FMRRMainWindow)
        self.lineEdit_RehabilitationProtocol.setGeometry(QtCore.QRect(65, 140, 621, 23))
        self.lineEdit_RehabilitationProtocol.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_RehabilitationProtocol.setObjectName("lineEdit_RehabilitationProtocol")
        self.lineEdit_MaxVel = QtWidgets.QLineEdit(FMRRMainWindow)
        self.lineEdit_MaxVel.setGeometry(QtCore.QRect(76, 514, 81, 22))
        self.lineEdit_MaxVel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lineEdit_MaxVel.setObjectName("lineEdit_MaxVel")
        self.spinBox_MaxVel = QtWidgets.QSpinBox(FMRRMainWindow)
        self.spinBox_MaxVel.setGeometry(QtCore.QRect(76, 539, 51, 22))
        self.spinBox_MaxVel.setMaximum(120)
        self.spinBox_MaxVel.setObjectName("spinBox_MaxVel")
        self.line_13 = QtWidgets.QFrame(FMRRMainWindow)
        self.line_13.setGeometry(QtCore.QRect(90, 620, 591, 31))
        self.line_13.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_13.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_13.setObjectName("line_13")
        self.spinBox_SinglePhaseDuration = QtWidgets.QSpinBox(FMRRMainWindow)
        self.spinBox_SinglePhaseDuration.setGeometry(QtCore.QRect(196, 539, 51, 22))
        self.spinBox_SinglePhaseDuration.setMaximum(999)
        self.spinBox_SinglePhaseDuration.setObjectName("spinBox_SinglePhaseDuration")
        self.lcdNumberExerciseTotalTime = QtWidgets.QLCDNumber(FMRRMainWindow)
        self.lcdNumberExerciseTotalTime.setGeometry(QtCore.QRect(393, 540, 42, 27))
        self.lcdNumberExerciseTotalTime.setDigitCount(2)
        self.lcdNumberExerciseTotalTime.setObjectName("lcdNumberExerciseTotalTime")
        self.lineEdit_ExerciseTotalTime = QtWidgets.QLineEdit(FMRRMainWindow)
        self.lineEdit_ExerciseTotalTime.setGeometry(QtCore.QRect(393, 515, 101, 22))
        self.lineEdit_ExerciseTotalTime.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lineEdit_ExerciseTotalTime.setObjectName("lineEdit_ExerciseTotalTime")
        self.lcdNumberMaxVelPhase01 = QtWidgets.QLCDNumber(FMRRMainWindow)
        self.lcdNumberMaxVelPhase01.setGeometry(QtCore.QRect(255, 199, 31, 27))
        font = QtGui.QFont()
        font.setKerning(True)
        self.lcdNumberMaxVelPhase01.setFont(font)
        self.lcdNumberMaxVelPhase01.setStyleSheet("color: rgb(0, 0, 0);")
        self.lcdNumberMaxVelPhase01.setDigitCount(2)
        self.lcdNumberMaxVelPhase01.setObjectName("lcdNumberMaxVelPhase01")
        self.lcdNumberMaxVelPhase02 = QtWidgets.QLCDNumber(FMRRMainWindow)
        self.lcdNumberMaxVelPhase02.setGeometry(QtCore.QRect(255, 228, 31, 27))
        self.lcdNumberMaxVelPhase02.setDigitCount(2)
        self.lcdNumberMaxVelPhase02.setObjectName("lcdNumberMaxVelPhase02")
        self.lcdNumberMaxVelPhase03 = QtWidgets.QLCDNumber(FMRRMainWindow)
        self.lcdNumberMaxVelPhase03.setGeometry(QtCore.QRect(255, 260, 31, 27))
        self.lcdNumberMaxVelPhase03.setDigitCount(2)
        self.lcdNumberMaxVelPhase03.setObjectName("lcdNumberMaxVelPhase03")
        self.lcdNumberMaxVelPhase04 = QtWidgets.QLCDNumber(FMRRMainWindow)
        self.lcdNumberMaxVelPhase04.setGeometry(QtCore.QRect(255, 290, 31, 27))
        self.lcdNumberMaxVelPhase04.setDigitCount(2)
        self.lcdNumberMaxVelPhase04.setObjectName("lcdNumberMaxVelPhase04")
        self.lcdNumberMaxVelPhase05 = QtWidgets.QLCDNumber(FMRRMainWindow)
        self.lcdNumberMaxVelPhase05.setGeometry(QtCore.QRect(255, 320, 31, 27))
        self.lcdNumberMaxVelPhase05.setDigitCount(2)
        self.lcdNumberMaxVelPhase05.setObjectName("lcdNumberMaxVelPhase05")
        self.lcdNumberMaxVelPhase06 = QtWidgets.QLCDNumber(FMRRMainWindow)
        self.lcdNumberMaxVelPhase06.setGeometry(QtCore.QRect(255, 350, 31, 27))
        self.lcdNumberMaxVelPhase06.setDigitCount(2)
        self.lcdNumberMaxVelPhase06.setObjectName("lcdNumberMaxVelPhase06")
        self.lcdNumberMaxVelPhase07 = QtWidgets.QLCDNumber(FMRRMainWindow)
        self.lcdNumberMaxVelPhase07.setGeometry(QtCore.QRect(255, 380, 31, 27))
        self.lcdNumberMaxVelPhase07.setDigitCount(2)
        self.lcdNumberMaxVelPhase07.setObjectName("lcdNumberMaxVelPhase07")
        self.lcdNumberMaxVelPhase08 = QtWidgets.QLCDNumber(FMRRMainWindow)
        self.lcdNumberMaxVelPhase08.setGeometry(QtCore.QRect(255, 410, 31, 27))
        self.lcdNumberMaxVelPhase08.setDigitCount(2)
        self.lcdNumberMaxVelPhase08.setObjectName("lcdNumberMaxVelPhase08")
        self.lcdNumberMaxVelPhase09 = QtWidgets.QLCDNumber(FMRRMainWindow)
        self.lcdNumberMaxVelPhase09.setGeometry(QtCore.QRect(255, 440, 31, 27))
        self.lcdNumberMaxVelPhase09.setDigitCount(2)
        self.lcdNumberMaxVelPhase09.setObjectName("lcdNumberMaxVelPhase09")
        self.lcdNumberMaxVelPhase10 = QtWidgets.QLCDNumber(FMRRMainWindow)
        self.lcdNumberMaxVelPhase10.setGeometry(QtCore.QRect(255, 470, 31, 27))
        self.lcdNumberMaxVelPhase10.setDigitCount(2)
        self.lcdNumberMaxVelPhase10.setObjectName("lcdNumberMaxVelPhase10")
        self.lcdNumberMaxVelPhase11 = QtWidgets.QLCDNumber(FMRRMainWindow)
        self.lcdNumberMaxVelPhase11.setGeometry(QtCore.QRect(575, 199, 31, 27))
        self.lcdNumberMaxVelPhase11.setDigitCount(2)
        self.lcdNumberMaxVelPhase11.setObjectName("lcdNumberMaxVelPhase11")
        self.lcdNumberMaxVelPhase12 = QtWidgets.QLCDNumber(FMRRMainWindow)
        self.lcdNumberMaxVelPhase12.setGeometry(QtCore.QRect(575, 229, 31, 27))
        self.lcdNumberMaxVelPhase12.setDigitCount(2)
        self.lcdNumberMaxVelPhase12.setObjectName("lcdNumberMaxVelPhase12")
        self.lcdNumberMaxVelPhase13 = QtWidgets.QLCDNumber(FMRRMainWindow)
        self.lcdNumberMaxVelPhase13.setGeometry(QtCore.QRect(575, 260, 31, 27))
        self.lcdNumberMaxVelPhase13.setDigitCount(2)
        self.lcdNumberMaxVelPhase13.setObjectName("lcdNumberMaxVelPhase13")
        self.lcdNumberMaxVelPhase14 = QtWidgets.QLCDNumber(FMRRMainWindow)
        self.lcdNumberMaxVelPhase14.setGeometry(QtCore.QRect(575, 290, 31, 27))
        self.lcdNumberMaxVelPhase14.setDigitCount(2)
        self.lcdNumberMaxVelPhase14.setObjectName("lcdNumberMaxVelPhase14")
        self.lcdNumberMaxVelPhase15 = QtWidgets.QLCDNumber(FMRRMainWindow)
        self.lcdNumberMaxVelPhase15.setGeometry(QtCore.QRect(575, 320, 31, 27))
        self.lcdNumberMaxVelPhase15.setDigitCount(2)
        self.lcdNumberMaxVelPhase15.setObjectName("lcdNumberMaxVelPhase15")
        self.lcdNumberMaxVelPhase16 = QtWidgets.QLCDNumber(FMRRMainWindow)
        self.lcdNumberMaxVelPhase16.setGeometry(QtCore.QRect(575, 350, 31, 27))
        self.lcdNumberMaxVelPhase16.setDigitCount(2)
        self.lcdNumberMaxVelPhase16.setObjectName("lcdNumberMaxVelPhase16")
        self.lcdNumberMaxVelPhase17 = QtWidgets.QLCDNumber(FMRRMainWindow)
        self.lcdNumberMaxVelPhase17.setGeometry(QtCore.QRect(575, 380, 31, 27))
        self.lcdNumberMaxVelPhase17.setDigitCount(2)
        self.lcdNumberMaxVelPhase17.setObjectName("lcdNumberMaxVelPhase17")
        self.lcdNumberMaxVelPhase18 = QtWidgets.QLCDNumber(FMRRMainWindow)
        self.lcdNumberMaxVelPhase18.setGeometry(QtCore.QRect(575, 410, 31, 27))
        self.lcdNumberMaxVelPhase18.setDigitCount(2)
        self.lcdNumberMaxVelPhase18.setObjectName("lcdNumberMaxVelPhase18")
        self.lcdNumberMaxVelPhase19 = QtWidgets.QLCDNumber(FMRRMainWindow)
        self.lcdNumberMaxVelPhase19.setGeometry(QtCore.QRect(575, 440, 31, 27))
        self.lcdNumberMaxVelPhase19.setDigitCount(2)
        self.lcdNumberMaxVelPhase19.setObjectName("lcdNumberMaxVelPhase19")
        self.lcdNumberMaxVelPhase20 = QtWidgets.QLCDNumber(FMRRMainWindow)
        self.lcdNumberMaxVelPhase20.setGeometry(QtCore.QRect(575, 470, 31, 27))
        self.lcdNumberMaxVelPhase20.setDigitCount(2)
        self.lcdNumberMaxVelPhase20.setObjectName("lcdNumberMaxVelPhase20")
        self.label = QtWidgets.QLabel(FMRRMainWindow)
        self.label.setGeometry(QtCore.QRect(195, 165, 91, 41))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(FMRRMainWindow)
        self.label_2.setGeometry(QtCore.QRect(515, 166, 91, 41))
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.pushButton_LoadCreateProtocol = QtWidgets.QPushButton(FMRRMainWindow)
        self.pushButton_LoadCreateProtocol.setEnabled(False)
        self.pushButton_LoadCreateProtocol.setGeometry(QtCore.QRect(185, 648, 100, 40))
        self.pushButton_LoadCreateProtocol.setObjectName("pushButton_LoadCreateProtocol")
        self.pushButton_SaveProtocol = QtWidgets.QPushButton(FMRRMainWindow)
        self.pushButton_SaveProtocol.setEnabled(False)
        self.pushButton_SaveProtocol.setGeometry(QtCore.QRect(295, 648, 100, 40))
        self.pushButton_SaveProtocol.setObjectName("pushButton_SaveProtocol")
        self.label_3 = QtWidgets.QLabel(FMRRMainWindow)
        self.label_3.setGeometry(QtCore.QRect(295, 180, 41, 21))
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.comboBoxModePhase01 = QtWidgets.QComboBox(FMRRMainWindow)
        self.comboBoxModePhase01.setGeometry(QtCore.QRect(295, 202, 71, 22))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.comboBoxModePhase01.setFont(font)
        self.comboBoxModePhase01.setObjectName("comboBoxModePhase01")
        self.comboBoxModePhase01.addItem("")
        self.comboBoxModePhase01.addItem("")
        self.comboBoxModePhase01.addItem("")
        self.comboBoxModePhase01.addItem("")
        self.comboBoxModePhase01.addItem("")
        self.comboBoxModePhase02 = QtWidgets.QComboBox(FMRRMainWindow)
        self.comboBoxModePhase02.setGeometry(QtCore.QRect(295, 232, 71, 22))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.comboBoxModePhase02.setFont(font)
        self.comboBoxModePhase02.setObjectName("comboBoxModePhase02")
        self.comboBoxModePhase02.addItem("")
        self.comboBoxModePhase02.addItem("")
        self.comboBoxModePhase02.addItem("")
        self.comboBoxModePhase02.addItem("")
        self.comboBoxModePhase02.addItem("")
        self.comboBoxModePhase03 = QtWidgets.QComboBox(FMRRMainWindow)
        self.comboBoxModePhase03.setGeometry(QtCore.QRect(295, 262, 71, 22))
        self.comboBoxModePhase03.setObjectName("comboBoxModePhase03")
        self.comboBoxModePhase03.addItem("")
        self.comboBoxModePhase03.addItem("")
        self.comboBoxModePhase03.addItem("")
        self.comboBoxModePhase03.addItem("")
        self.comboBoxModePhase03.addItem("")
        self.comboBoxModePhase04 = QtWidgets.QComboBox(FMRRMainWindow)
        self.comboBoxModePhase04.setGeometry(QtCore.QRect(295, 293, 71, 22))
        self.comboBoxModePhase04.setObjectName("comboBoxModePhase04")
        self.comboBoxModePhase04.addItem("")
        self.comboBoxModePhase04.addItem("")
        self.comboBoxModePhase04.addItem("")
        self.comboBoxModePhase04.addItem("")
        self.comboBoxModePhase04.addItem("")
        self.comboBoxModePhase05 = QtWidgets.QComboBox(FMRRMainWindow)
        self.comboBoxModePhase05.setGeometry(QtCore.QRect(295, 323, 71, 22))
        self.comboBoxModePhase05.setObjectName("comboBoxModePhase05")
        self.comboBoxModePhase05.addItem("")
        self.comboBoxModePhase05.addItem("")
        self.comboBoxModePhase05.addItem("")
        self.comboBoxModePhase05.addItem("")
        self.comboBoxModePhase05.addItem("")
        self.comboBoxModePhase06 = QtWidgets.QComboBox(FMRRMainWindow)
        self.comboBoxModePhase06.setGeometry(QtCore.QRect(295, 353, 71, 22))
        self.comboBoxModePhase06.setObjectName("comboBoxModePhase06")
        self.comboBoxModePhase06.addItem("")
        self.comboBoxModePhase06.addItem("")
        self.comboBoxModePhase06.addItem("")
        self.comboBoxModePhase06.addItem("")
        self.comboBoxModePhase06.addItem("")
        self.comboBoxModePhase07 = QtWidgets.QComboBox(FMRRMainWindow)
        self.comboBoxModePhase07.setGeometry(QtCore.QRect(295, 383, 71, 22))
        self.comboBoxModePhase07.setObjectName("comboBoxModePhase07")
        self.comboBoxModePhase07.addItem("")
        self.comboBoxModePhase07.addItem("")
        self.comboBoxModePhase07.addItem("")
        self.comboBoxModePhase07.addItem("")
        self.comboBoxModePhase07.addItem("")
        self.comboBoxModePhase08 = QtWidgets.QComboBox(FMRRMainWindow)
        self.comboBoxModePhase08.setGeometry(QtCore.QRect(295, 413, 71, 22))
        self.comboBoxModePhase08.setObjectName("comboBoxModePhase08")
        self.comboBoxModePhase08.addItem("")
        self.comboBoxModePhase08.addItem("")
        self.comboBoxModePhase08.addItem("")
        self.comboBoxModePhase08.addItem("")
        self.comboBoxModePhase08.addItem("")
        self.comboBoxModePhase09 = QtWidgets.QComboBox(FMRRMainWindow)
        self.comboBoxModePhase09.setGeometry(QtCore.QRect(295, 442, 71, 22))
        self.comboBoxModePhase09.setObjectName("comboBoxModePhase09")
        self.comboBoxModePhase09.addItem("")
        self.comboBoxModePhase09.addItem("")
        self.comboBoxModePhase09.addItem("")
        self.comboBoxModePhase09.addItem("")
        self.comboBoxModePhase09.addItem("")
        self.comboBoxModePhase10 = QtWidgets.QComboBox(FMRRMainWindow)
        self.comboBoxModePhase10.setGeometry(QtCore.QRect(295, 473, 71, 22))
        self.comboBoxModePhase10.setObjectName("comboBoxModePhase10")
        self.comboBoxModePhase10.addItem("")
        self.comboBoxModePhase10.addItem("")
        self.comboBoxModePhase10.addItem("")
        self.comboBoxModePhase10.addItem("")
        self.comboBoxModePhase10.addItem("")
        self.comboBoxModePhase11 = QtWidgets.QComboBox(FMRRMainWindow)
        self.comboBoxModePhase11.setGeometry(QtCore.QRect(615, 203, 71, 22))
        self.comboBoxModePhase11.setObjectName("comboBoxModePhase11")
        self.comboBoxModePhase11.addItem("")
        self.comboBoxModePhase11.addItem("")
        self.comboBoxModePhase11.addItem("")
        self.comboBoxModePhase11.addItem("")
        self.comboBoxModePhase11.addItem("")
        self.comboBoxModePhase12 = QtWidgets.QComboBox(FMRRMainWindow)
        self.comboBoxModePhase12.setGeometry(QtCore.QRect(615, 233, 71, 22))
        self.comboBoxModePhase12.setObjectName("comboBoxModePhase12")
        self.comboBoxModePhase12.addItem("")
        self.comboBoxModePhase12.addItem("")
        self.comboBoxModePhase12.addItem("")
        self.comboBoxModePhase12.addItem("")
        self.comboBoxModePhase12.addItem("")
        self.comboBoxModePhase13 = QtWidgets.QComboBox(FMRRMainWindow)
        self.comboBoxModePhase13.setGeometry(QtCore.QRect(615, 263, 71, 22))
        self.comboBoxModePhase13.setObjectName("comboBoxModePhase13")
        self.comboBoxModePhase13.addItem("")
        self.comboBoxModePhase13.addItem("")
        self.comboBoxModePhase13.addItem("")
        self.comboBoxModePhase13.addItem("")
        self.comboBoxModePhase13.addItem("")
        self.comboBoxModePhase14 = QtWidgets.QComboBox(FMRRMainWindow)
        self.comboBoxModePhase14.setGeometry(QtCore.QRect(615, 293, 71, 22))
        self.comboBoxModePhase14.setObjectName("comboBoxModePhase14")
        self.comboBoxModePhase14.addItem("")
        self.comboBoxModePhase14.addItem("")
        self.comboBoxModePhase14.addItem("")
        self.comboBoxModePhase14.addItem("")
        self.comboBoxModePhase14.addItem("")
        self.comboBoxModePhase15 = QtWidgets.QComboBox(FMRRMainWindow)
        self.comboBoxModePhase15.setGeometry(QtCore.QRect(615, 323, 71, 22))
        self.comboBoxModePhase15.setObjectName("comboBoxModePhase15")
        self.comboBoxModePhase15.addItem("")
        self.comboBoxModePhase15.addItem("")
        self.comboBoxModePhase15.addItem("")
        self.comboBoxModePhase15.addItem("")
        self.comboBoxModePhase15.addItem("")
        self.comboBoxModePhase16 = QtWidgets.QComboBox(FMRRMainWindow)
        self.comboBoxModePhase16.setGeometry(QtCore.QRect(615, 353, 71, 22))
        self.comboBoxModePhase16.setObjectName("comboBoxModePhase16")
        self.comboBoxModePhase16.addItem("")
        self.comboBoxModePhase16.addItem("")
        self.comboBoxModePhase16.addItem("")
        self.comboBoxModePhase16.addItem("")
        self.comboBoxModePhase16.addItem("")
        self.comboBoxModePhase17 = QtWidgets.QComboBox(FMRRMainWindow)
        self.comboBoxModePhase17.setGeometry(QtCore.QRect(615, 383, 71, 22))
        self.comboBoxModePhase17.setObjectName("comboBoxModePhase17")
        self.comboBoxModePhase17.addItem("")
        self.comboBoxModePhase17.addItem("")
        self.comboBoxModePhase17.addItem("")
        self.comboBoxModePhase17.addItem("")
        self.comboBoxModePhase17.addItem("")
        self.comboBoxModePhase18 = QtWidgets.QComboBox(FMRRMainWindow)
        self.comboBoxModePhase18.setGeometry(QtCore.QRect(615, 413, 71, 22))
        self.comboBoxModePhase18.setObjectName("comboBoxModePhase18")
        self.comboBoxModePhase18.addItem("")
        self.comboBoxModePhase18.addItem("")
        self.comboBoxModePhase18.addItem("")
        self.comboBoxModePhase18.addItem("")
        self.comboBoxModePhase18.addItem("")
        self.comboBoxModePhase19 = QtWidgets.QComboBox(FMRRMainWindow)
        self.comboBoxModePhase19.setGeometry(QtCore.QRect(615, 443, 71, 22))
        self.comboBoxModePhase19.setObjectName("comboBoxModePhase19")
        self.comboBoxModePhase19.addItem("")
        self.comboBoxModePhase19.addItem("")
        self.comboBoxModePhase19.addItem("")
        self.comboBoxModePhase19.addItem("")
        self.comboBoxModePhase19.addItem("")
        self.comboBoxModePhase20 = QtWidgets.QComboBox(FMRRMainWindow)
        self.comboBoxModePhase20.setGeometry(QtCore.QRect(615, 473, 71, 22))
        self.comboBoxModePhase20.setObjectName("comboBoxModePhase20")
        self.comboBoxModePhase20.addItem("")
        self.comboBoxModePhase20.addItem("")
        self.comboBoxModePhase20.addItem("")
        self.comboBoxModePhase20.addItem("")
        self.comboBoxModePhase20.addItem("")
        self.pushButton_STARTtrainig = QtWidgets.QPushButton(FMRRMainWindow)
        self.pushButton_STARTtrainig.setEnabled(False)
        self.pushButton_STARTtrainig.setGeometry(QtCore.QRect(200, 580, 100, 40))
        self.pushButton_STARTtrainig.setObjectName("pushButton_STARTtrainig")
        self.pushButton_PAUSEtrainig = QtWidgets.QPushButton(FMRRMainWindow)
        self.pushButton_PAUSEtrainig.setEnabled(False)
        self.pushButton_PAUSEtrainig.setGeometry(QtCore.QRect(310, 580, 100, 40))
        self.pushButton_PAUSEtrainig.setObjectName("pushButton_PAUSEtrainig")
        self.pushButton_STOPtrainig = QtWidgets.QPushButton(FMRRMainWindow)
        self.pushButton_STOPtrainig.setEnabled(False)
        self.pushButton_STOPtrainig.setGeometry(QtCore.QRect(420, 580, 100, 40))
        self.pushButton_STOPtrainig.setObjectName("pushButton_STOPtrainig")
        self.pushButton_LoadCreateMovement = QtWidgets.QPushButton(FMRRMainWindow)
        self.pushButton_LoadCreateMovement.setGeometry(QtCore.QRect(76, 648, 100, 40))
        self.pushButton_LoadCreateMovement.setObjectName("pushButton_LoadCreateMovement")
        self.radioButton_TypeOfExercise_Reaching = QtWidgets.QRadioButton(FMRRMainWindow)
        self.radioButton_TypeOfExercise_Reaching.setGeometry(QtCore.QRect(70, 94, 101, 17))
        self.radioButton_TypeOfExercise_Reaching.setChecked(False)
        self.radioButton_TypeOfExercise_Reaching.setObjectName("radioButton_TypeOfExercise_Reaching")
        self.line_6 = QtWidgets.QFrame(FMRRMainWindow)
        self.line_6.setGeometry(QtCore.QRect(700, 180, 20, 441))
        self.line_6.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.lineEdit_TypeOfExercise = QtWidgets.QLineEdit(FMRRMainWindow)
        self.lineEdit_TypeOfExercise.setGeometry(QtCore.QRect(65, 64, 101, 22))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lineEdit_TypeOfExercise.setFont(font)
        self.lineEdit_TypeOfExercise.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lineEdit_TypeOfExercise.setObjectName("lineEdit_TypeOfExercise")
        self.radioButton_TypeOfExercise_HandtoMouth = QtWidgets.QRadioButton(FMRRMainWindow)
        self.radioButton_TypeOfExercise_HandtoMouth.setGeometry(QtCore.QRect(70, 114, 111, 17))
        self.radioButton_TypeOfExercise_HandtoMouth.setChecked(True)
        self.radioButton_TypeOfExercise_HandtoMouth.setObjectName("radioButton_TypeOfExercise_HandtoMouth")
        self.lineEdit_MovementName = QtWidgets.QLineEdit(FMRRMainWindow)
        self.lineEdit_MovementName.setGeometry(QtCore.QRect(65, 40, 211, 20))
        self.lineEdit_MovementName.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_MovementName.setObjectName("lineEdit_MovementName")
        self.lineEdit_ExerciseMovementCOUNT = QtWidgets.QLineEdit(FMRRMainWindow)
        self.lineEdit_ExerciseMovementCOUNT.setGeometry(QtCore.QRect(566, 516, 121, 22))
        self.lineEdit_ExerciseMovementCOUNT.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_ExerciseMovementCOUNT.setObjectName("lineEdit_ExerciseMovementCOUNT")
        self.lcdNumber_MovementCOUNT = QtWidgets.QLCDNumber(FMRRMainWindow)
        self.lcdNumber_MovementCOUNT.setGeometry(QtCore.QRect(570, 540, 42, 27))
        self.lcdNumber_MovementCOUNT.setDigitCount(3)
        self.lcdNumber_MovementCOUNT.setObjectName("lcdNumber_MovementCOUNT")
        self.graphicsView = QtWidgets.QGraphicsView(FMRRMainWindow)
        self.graphicsView.setGeometry(QtCore.QRect(750, 130, 691, 491))
        self.graphicsView.setObjectName("graphicsView")
        self.line_14 = QtWidgets.QFrame(FMRRMainWindow)
        self.line_14.setGeometry(QtCore.QRect(730, 620, 711, 31))
        self.line_14.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_14.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_14.setObjectName("line_14")
        self.pushButton_DATAacquisition = QtWidgets.QPushButton(FMRRMainWindow)
        self.pushButton_DATAacquisition.setGeometry(QtCore.QRect(760, 650, 100, 40))
        self.pushButton_DATAacquisition.setObjectName("pushButton_DATAacquisition")
        self.lineEdit_Side = QtWidgets.QLineEdit(FMRRMainWindow)
        self.lineEdit_Side.setGeometry(QtCore.QRect(176, 64, 91, 22))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setItalic(False)
        self.lineEdit_Side.setFont(font)
        self.lineEdit_Side.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lineEdit_Side.setObjectName("lineEdit_Side")
        self.pushButton_CLOSEprogram = QtWidgets.QPushButton(FMRRMainWindow)
        self.pushButton_CLOSEprogram.setGeometry(QtCore.QRect(610, 650, 100, 40))
        self.pushButton_CLOSEprogram.setObjectName("pushButton_CLOSEprogram")
        self.lineEdit_SinglePhaseDuration = QtWidgets.QLineEdit(FMRRMainWindow)
        self.lineEdit_SinglePhaseDuration.setGeometry(QtCore.QRect(197, 514, 111, 22))
        self.lineEdit_SinglePhaseDuration.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lineEdit_SinglePhaseDuration.setObjectName("lineEdit_SinglePhaseDuration")
        self.groupBox = QtWidgets.QGroupBox(FMRRMainWindow)
        self.groupBox.setGeometry(QtCore.QRect(176, 74, 81, 61))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.radioButton_SideLeft = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_SideLeft.setGeometry(QtCore.QRect(10, 20, 82, 17))
        self.radioButton_SideLeft.setChecked(False)
        self.radioButton_SideLeft.setObjectName("radioButton_SideLeft")
        self.radioButton_SideRight = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_SideRight.setGeometry(QtCore.QRect(10, 40, 91, 17))
        self.radioButton_SideRight.setChecked(True)
        self.radioButton_SideRight.setObjectName("radioButton_SideRight")
        self.lineEdit_Side_2 = QtWidgets.QLineEdit(FMRRMainWindow)
        self.lineEdit_Side_2.setGeometry(QtCore.QRect(278, 64, 91, 22))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setItalic(False)
        self.lineEdit_Side_2.setFont(font)
        self.lineEdit_Side_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lineEdit_Side_2.setObjectName("lineEdit_Side_2")
        self.groupBox_2 = QtWidgets.QGroupBox(FMRRMainWindow)
        self.groupBox_2.setGeometry(QtCore.QRect(280, 64, 101, 71))
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.radioButton_VelocityProfileBellshaped = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButton_VelocityProfileBellshaped.setGeometry(QtCore.QRect(10, 50, 82, 17))
        self.radioButton_VelocityProfileBellshaped.setChecked(True)
        self.radioButton_VelocityProfileBellshaped.setObjectName("radioButton_VelocityProfileBellshaped")
        self.radioButton = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButton.setGeometry(QtCore.QRect(10, 30, 82, 17))
        self.radioButton.setObjectName("radioButton")

        self.retranslateUi(FMRRMainWindow)
        QtCore.QMetaObject.connectSlotsByName(FMRRMainWindow)
        FMRRMainWindow.setTabOrder(self.lineEdit_RehabilitationProtocol, self.spinBoxPercPhase01)
        FMRRMainWindow.setTabOrder(self.spinBoxPercPhase01, self.spinBoxPercPhase02)
        FMRRMainWindow.setTabOrder(self.spinBoxPercPhase02, self.spinBoxPercPhase03)
        FMRRMainWindow.setTabOrder(self.spinBoxPercPhase03, self.spinBoxPercPhase04)
        FMRRMainWindow.setTabOrder(self.spinBoxPercPhase04, self.spinBoxPercPhase05)
        FMRRMainWindow.setTabOrder(self.spinBoxPercPhase05, self.spinBoxPercPhase06)
        FMRRMainWindow.setTabOrder(self.spinBoxPercPhase06, self.spinBoxPercPhase07)
        FMRRMainWindow.setTabOrder(self.spinBoxPercPhase07, self.spinBoxPercPhase08)
        FMRRMainWindow.setTabOrder(self.spinBoxPercPhase08, self.spinBoxPercPhase09)
        FMRRMainWindow.setTabOrder(self.spinBoxPercPhase09, self.spinBoxPercPhase10)
        FMRRMainWindow.setTabOrder(self.spinBoxPercPhase10, self.spinBoxPercPhase11)
        FMRRMainWindow.setTabOrder(self.spinBoxPercPhase11, self.spinBoxPercPhase12)
        FMRRMainWindow.setTabOrder(self.spinBoxPercPhase12, self.spinBoxPercPhase13)
        FMRRMainWindow.setTabOrder(self.spinBoxPercPhase13, self.spinBoxPercPhase14)
        FMRRMainWindow.setTabOrder(self.spinBoxPercPhase14, self.spinBoxPercPhase15)
        FMRRMainWindow.setTabOrder(self.spinBoxPercPhase15, self.spinBoxPercPhase16)
        FMRRMainWindow.setTabOrder(self.spinBoxPercPhase16, self.spinBoxPercPhase17)
        FMRRMainWindow.setTabOrder(self.spinBoxPercPhase17, self.spinBoxPercPhase18)
        FMRRMainWindow.setTabOrder(self.spinBoxPercPhase18, self.spinBoxPercPhase19)
        FMRRMainWindow.setTabOrder(self.spinBoxPercPhase19, self.spinBoxPercPhase20)
        FMRRMainWindow.setTabOrder(self.spinBoxPercPhase20, self.lineEdit_MaxVel)
        FMRRMainWindow.setTabOrder(self.lineEdit_MaxVel, self.spinBox_MaxVel)
        FMRRMainWindow.setTabOrder(self.spinBox_MaxVel, self.spinBox_SinglePhaseDuration)
        FMRRMainWindow.setTabOrder(self.spinBox_SinglePhaseDuration, self.lineEdit_ExerciseTotalTime)
        FMRRMainWindow.setTabOrder(self.lineEdit_ExerciseTotalTime, self.pushButton_LoadCreateProtocol)
        FMRRMainWindow.setTabOrder(self.pushButton_LoadCreateProtocol, self.pushButton_SaveProtocol)

    def retranslateUi(self, FMRRMainWindow):
        _translate = QtCore.QCoreApplication.translate
        FMRRMainWindow.setWindowTitle(_translate("FMRRMainWindow", "Dialog"))
        self.lineEdit_RehabilitationProtocol.setText(_translate("FMRRMainWindow", "NAME of  PROTOCOL"))
        self.lineEdit_MaxVel.setText(_translate("FMRRMainWindow", "Vmax (cm/s)"))
        self.lineEdit_ExerciseTotalTime.setText(_translate("FMRRMainWindow", "Total time (min)"))
        self.label.setText(_translate("FMRRMainWindow", "Vmax \n"
" Perc          cm/s"))
        self.label_2.setText(_translate("FMRRMainWindow", "Vmax \n"
" Perc          cm/s"))
        self.pushButton_LoadCreateProtocol.setText(_translate("FMRRMainWindow", "LOAD / CREATE \n"
" protocol"))
        self.pushButton_SaveProtocol.setText(_translate("FMRRMainWindow", "SAVE \n"
" protocol"))
        self.label_3.setText(_translate("FMRRMainWindow", "Mode"))
        self.comboBoxModePhase01.setItemText(0, _translate("FMRRMainWindow", "Velocity"))
        self.comboBoxModePhase01.setItemText(1, _translate("FMRRMainWindow", "Force"))
        self.comboBoxModePhase01.setItemText(2, _translate("FMRRMainWindow", "EMG"))
        self.comboBoxModePhase01.setItemText(3, _translate("FMRRMainWindow", "MixedForce"))
        self.comboBoxModePhase01.setItemText(4, _translate("FMRRMainWindow", "MixedEMG"))
        self.comboBoxModePhase02.setItemText(0, _translate("FMRRMainWindow", "Velocity"))
        self.comboBoxModePhase02.setItemText(1, _translate("FMRRMainWindow", "Force"))
        self.comboBoxModePhase02.setItemText(2, _translate("FMRRMainWindow", "EMG"))
        self.comboBoxModePhase02.setItemText(3, _translate("FMRRMainWindow", "MixedForce"))
        self.comboBoxModePhase02.setItemText(4, _translate("FMRRMainWindow", "MixedEMG"))
        self.comboBoxModePhase03.setItemText(0, _translate("FMRRMainWindow", "Velocity"))
        self.comboBoxModePhase03.setItemText(1, _translate("FMRRMainWindow", "Force"))
        self.comboBoxModePhase03.setItemText(2, _translate("FMRRMainWindow", "EMG"))
        self.comboBoxModePhase03.setItemText(3, _translate("FMRRMainWindow", "MixedForce"))
        self.comboBoxModePhase03.setItemText(4, _translate("FMRRMainWindow", "MixedEMG"))
        self.comboBoxModePhase04.setItemText(0, _translate("FMRRMainWindow", "Velocity"))
        self.comboBoxModePhase04.setItemText(1, _translate("FMRRMainWindow", "Force"))
        self.comboBoxModePhase04.setItemText(2, _translate("FMRRMainWindow", "EMG"))
        self.comboBoxModePhase04.setItemText(3, _translate("FMRRMainWindow", "MixedForce"))
        self.comboBoxModePhase04.setItemText(4, _translate("FMRRMainWindow", "MixedEMG"))
        self.comboBoxModePhase05.setItemText(0, _translate("FMRRMainWindow", "Velocity"))
        self.comboBoxModePhase05.setItemText(1, _translate("FMRRMainWindow", "Force"))
        self.comboBoxModePhase05.setItemText(2, _translate("FMRRMainWindow", "EMG"))
        self.comboBoxModePhase05.setItemText(3, _translate("FMRRMainWindow", "MixedForce"))
        self.comboBoxModePhase05.setItemText(4, _translate("FMRRMainWindow", "MixedEMG"))
        self.comboBoxModePhase06.setItemText(0, _translate("FMRRMainWindow", "Velocity"))
        self.comboBoxModePhase06.setItemText(1, _translate("FMRRMainWindow", "Force"))
        self.comboBoxModePhase06.setItemText(2, _translate("FMRRMainWindow", "EMG"))
        self.comboBoxModePhase06.setItemText(3, _translate("FMRRMainWindow", "MixedForce"))
        self.comboBoxModePhase06.setItemText(4, _translate("FMRRMainWindow", "MixedEMG"))
        self.comboBoxModePhase07.setItemText(0, _translate("FMRRMainWindow", "Velocity"))
        self.comboBoxModePhase07.setItemText(1, _translate("FMRRMainWindow", "Force"))
        self.comboBoxModePhase07.setItemText(2, _translate("FMRRMainWindow", "EMG"))
        self.comboBoxModePhase07.setItemText(3, _translate("FMRRMainWindow", "MixedForce"))
        self.comboBoxModePhase07.setItemText(4, _translate("FMRRMainWindow", "MixedEMG"))
        self.comboBoxModePhase08.setItemText(0, _translate("FMRRMainWindow", "Velocity"))
        self.comboBoxModePhase08.setItemText(1, _translate("FMRRMainWindow", "Force"))
        self.comboBoxModePhase08.setItemText(2, _translate("FMRRMainWindow", "EMG"))
        self.comboBoxModePhase08.setItemText(3, _translate("FMRRMainWindow", "MixedForce"))
        self.comboBoxModePhase08.setItemText(4, _translate("FMRRMainWindow", "MixedEMG"))
        self.comboBoxModePhase09.setItemText(0, _translate("FMRRMainWindow", "Velocity"))
        self.comboBoxModePhase09.setItemText(1, _translate("FMRRMainWindow", "Force"))
        self.comboBoxModePhase09.setItemText(2, _translate("FMRRMainWindow", "EMG"))
        self.comboBoxModePhase09.setItemText(3, _translate("FMRRMainWindow", "MixedForce"))
        self.comboBoxModePhase09.setItemText(4, _translate("FMRRMainWindow", "MixedEMG"))
        self.comboBoxModePhase10.setItemText(0, _translate("FMRRMainWindow", "Velocity"))
        self.comboBoxModePhase10.setItemText(1, _translate("FMRRMainWindow", "Force"))
        self.comboBoxModePhase10.setItemText(2, _translate("FMRRMainWindow", "EMG"))
        self.comboBoxModePhase10.setItemText(3, _translate("FMRRMainWindow", "MixedForce"))
        self.comboBoxModePhase10.setItemText(4, _translate("FMRRMainWindow", "MixedEMG"))
        self.comboBoxModePhase11.setItemText(0, _translate("FMRRMainWindow", "Velocity"))
        self.comboBoxModePhase11.setItemText(1, _translate("FMRRMainWindow", "Force"))
        self.comboBoxModePhase11.setItemText(2, _translate("FMRRMainWindow", "EMG"))
        self.comboBoxModePhase11.setItemText(3, _translate("FMRRMainWindow", "MixedForce"))
        self.comboBoxModePhase11.setItemText(4, _translate("FMRRMainWindow", "MixedEMG"))
        self.comboBoxModePhase12.setItemText(0, _translate("FMRRMainWindow", "Velocity"))
        self.comboBoxModePhase12.setItemText(1, _translate("FMRRMainWindow", "Force"))
        self.comboBoxModePhase12.setItemText(2, _translate("FMRRMainWindow", "EMG"))
        self.comboBoxModePhase12.setItemText(3, _translate("FMRRMainWindow", "MixedForce"))
        self.comboBoxModePhase12.setItemText(4, _translate("FMRRMainWindow", "MixedEMG"))
        self.comboBoxModePhase13.setItemText(0, _translate("FMRRMainWindow", "Velocity"))
        self.comboBoxModePhase13.setItemText(1, _translate("FMRRMainWindow", "Force"))
        self.comboBoxModePhase13.setItemText(2, _translate("FMRRMainWindow", "EMG"))
        self.comboBoxModePhase13.setItemText(3, _translate("FMRRMainWindow", "MixedForce"))
        self.comboBoxModePhase13.setItemText(4, _translate("FMRRMainWindow", "MixedEMG"))
        self.comboBoxModePhase14.setItemText(0, _translate("FMRRMainWindow", "Velocity"))
        self.comboBoxModePhase14.setItemText(1, _translate("FMRRMainWindow", "Force"))
        self.comboBoxModePhase14.setItemText(2, _translate("FMRRMainWindow", "EMG"))
        self.comboBoxModePhase14.setItemText(3, _translate("FMRRMainWindow", "MixedForce"))
        self.comboBoxModePhase14.setItemText(4, _translate("FMRRMainWindow", "MixedEMG"))
        self.comboBoxModePhase15.setItemText(0, _translate("FMRRMainWindow", "Velocity"))
        self.comboBoxModePhase15.setItemText(1, _translate("FMRRMainWindow", "Force"))
        self.comboBoxModePhase15.setItemText(2, _translate("FMRRMainWindow", "EMG"))
        self.comboBoxModePhase15.setItemText(3, _translate("FMRRMainWindow", "MixedForce"))
        self.comboBoxModePhase15.setItemText(4, _translate("FMRRMainWindow", "MixedEMG"))
        self.comboBoxModePhase16.setItemText(0, _translate("FMRRMainWindow", "Velocity"))
        self.comboBoxModePhase16.setItemText(1, _translate("FMRRMainWindow", "Force"))
        self.comboBoxModePhase16.setItemText(2, _translate("FMRRMainWindow", "EMG"))
        self.comboBoxModePhase16.setItemText(3, _translate("FMRRMainWindow", "MixedForce"))
        self.comboBoxModePhase16.setItemText(4, _translate("FMRRMainWindow", "MixedEMG"))
        self.comboBoxModePhase17.setItemText(0, _translate("FMRRMainWindow", "Velocity"))
        self.comboBoxModePhase17.setItemText(1, _translate("FMRRMainWindow", "Force"))
        self.comboBoxModePhase17.setItemText(2, _translate("FMRRMainWindow", "EMG"))
        self.comboBoxModePhase17.setItemText(3, _translate("FMRRMainWindow", "MixedForce"))
        self.comboBoxModePhase17.setItemText(4, _translate("FMRRMainWindow", "MixedEMG"))
        self.comboBoxModePhase18.setItemText(0, _translate("FMRRMainWindow", "Velocity"))
        self.comboBoxModePhase18.setItemText(1, _translate("FMRRMainWindow", "Force"))
        self.comboBoxModePhase18.setItemText(2, _translate("FMRRMainWindow", "EMG"))
        self.comboBoxModePhase18.setItemText(3, _translate("FMRRMainWindow", "MixedForce"))
        self.comboBoxModePhase18.setItemText(4, _translate("FMRRMainWindow", "MixedEMG"))
        self.comboBoxModePhase19.setItemText(0, _translate("FMRRMainWindow", "Velocity"))
        self.comboBoxModePhase19.setItemText(1, _translate("FMRRMainWindow", "Force"))
        self.comboBoxModePhase19.setItemText(2, _translate("FMRRMainWindow", "EMG"))
        self.comboBoxModePhase19.setItemText(3, _translate("FMRRMainWindow", "MixedForce"))
        self.comboBoxModePhase19.setItemText(4, _translate("FMRRMainWindow", "MixedEMG"))
        self.comboBoxModePhase20.setItemText(0, _translate("FMRRMainWindow", "Velocity"))
        self.comboBoxModePhase20.setItemText(1, _translate("FMRRMainWindow", "Force"))
        self.comboBoxModePhase20.setItemText(2, _translate("FMRRMainWindow", "EMG"))
        self.comboBoxModePhase20.setItemText(3, _translate("FMRRMainWindow", "MixedForce"))
        self.comboBoxModePhase20.setItemText(4, _translate("FMRRMainWindow", "MixedEMG"))
        self.pushButton_STARTtrainig.setText(_translate("FMRRMainWindow", "START training"))
        self.pushButton_PAUSEtrainig.setText(_translate("FMRRMainWindow", "PAUSE training"))
        self.pushButton_STOPtrainig.setText(_translate("FMRRMainWindow", "STOP training"))
        self.pushButton_LoadCreateMovement.setText(_translate("FMRRMainWindow", "LOAD / CREATE \n"
" movement"))
        self.radioButton_TypeOfExercise_Reaching.setText(_translate("FMRRMainWindow", "Reaching"))
        self.lineEdit_TypeOfExercise.setText(_translate("FMRRMainWindow", "Type of exercise"))
        self.radioButton_TypeOfExercise_HandtoMouth.setText(_translate("FMRRMainWindow", "Hand to mouth"))
        self.lineEdit_MovementName.setText(_translate("FMRRMainWindow", "NAME of MOVEMENT "))
        self.lineEdit_ExerciseMovementCOUNT.setText(_translate("FMRRMainWindow", "Movement COUNT"))
        self.pushButton_DATAacquisition.setText(_translate("FMRRMainWindow", "DATA \n"
" acquisition"))
        self.lineEdit_Side.setText(_translate("FMRRMainWindow", "Side"))
        self.pushButton_CLOSEprogram.setText(_translate("FMRRMainWindow", "CLOSE \n"
" program"))
        self.lineEdit_SinglePhaseDuration.setText(_translate("FMRRMainWindow", "Phase duration (s)"))
        self.radioButton_SideLeft.setText(_translate("FMRRMainWindow", "Left"))
        self.radioButton_SideRight.setText(_translate("FMRRMainWindow", "Right"))
        self.lineEdit_Side_2.setText(_translate("FMRRMainWindow", "Velocity Profile"))
        self.radioButton_VelocityProfileBellshaped.setText(_translate("FMRRMainWindow", "Bell shaped"))
        self.radioButton.setText(_translate("FMRRMainWindow", "Constant"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    FMRRMainWindow = QtWidgets.QDialog()
    ui = Ui_FMRRMainWindow()
    ui.setupUi(FMRRMainWindow)
    FMRRMainWindow.show()
    sys.exit(app.exec_())
