# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\MovementWindow.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
from . import MC_Tools

class Ui_MovementWindow(object):
    def __init__(self) -> None:
        pass
    
    def setupUi(self, MovementWindow):
        MovementWindow.setObjectName("MovementWindow")
        MovementWindow.resize(1615, 933)
        self.pushButton_SaveStartPosition = QtWidgets.QPushButton(MovementWindow)
        self.pushButton_SaveStartPosition.setGeometry(QtCore.QRect(240, 540, 171, 40))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_SaveStartPosition.setFont(font)
        self.pushButton_SaveStartPosition.setObjectName("pushButton_SaveStartPosition")
        self.pushButton_LoadJointPosition = QtWidgets.QPushButton(MovementWindow)
        self.pushButton_LoadJointPosition.setGeometry(QtCore.QRect(264, 230, 120, 40))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_LoadJointPosition.setFont(font)
        self.pushButton_LoadJointPosition.setObjectName("pushButton_LoadJointPosition")
        self.line_6 = QtWidgets.QFrame(MovementWindow)
        self.line_6.setGeometry(QtCore.QRect(210, 110, 20, 481))
        self.line_6.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.pushButton_Xminus = QtWidgets.QPushButton(MovementWindow)
        self.pushButton_Xminus.setGeometry(QtCore.QRect(40, 150, 30, 30))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_Xminus.setFont(font)
        self.pushButton_Xminus.setObjectName("pushButton_Xminus")
        self.pushButton_Xplus = QtWidgets.QPushButton(MovementWindow)
        self.pushButton_Xplus.setGeometry(QtCore.QRect(80, 150, 30, 30))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_Xplus.setFont(font)
        self.pushButton_Xplus.setObjectName("pushButton_Xplus")
        self.lineEdit_MoveRobot = QtWidgets.QLineEdit(MovementWindow)
        self.lineEdit_MoveRobot.setGeometry(QtCore.QRect(30, 60, 391, 23))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lineEdit_MoveRobot.setFont(font)
        self.lineEdit_MoveRobot.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_MoveRobot.setObjectName("lineEdit_MoveRobot")
        self.pushButton_Yminus = QtWidgets.QPushButton(MovementWindow)
        self.pushButton_Yminus.setGeometry(QtCore.QRect(40, 190, 30, 30))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_Yminus.setFont(font)
        self.pushButton_Yminus.setObjectName("pushButton_Yminus")
        self.pushButton_Yplus = QtWidgets.QPushButton(MovementWindow)
        self.pushButton_Yplus.setGeometry(QtCore.QRect(80, 190, 30, 30))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_Yplus.setFont(font)
        self.pushButton_Yplus.setObjectName("pushButton_Yplus")
        self.pushButton_Zminus = QtWidgets.QPushButton(MovementWindow)
        self.pushButton_Zminus.setGeometry(QtCore.QRect(40, 230, 30, 30))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_Zminus.setFont(font)
        self.pushButton_Zminus.setObjectName("pushButton_Zminus")
        self.pushButton_Zplus = QtWidgets.QPushButton(MovementWindow)
        self.pushButton_Zplus.setGeometry(QtCore.QRect(80, 230, 30, 30))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_Zplus.setFont(font)
        self.pushButton_Zplus.setObjectName("pushButton_Zplus")
        self.spinBox_MoveRobotTranslationalVelocity = QtWidgets.QSpinBox(MovementWindow)
        self.spinBox_MoveRobotTranslationalVelocity.setGeometry(QtCore.QRect(150, 110, 42, 22))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.spinBox_MoveRobotTranslationalVelocity.setFont(font)
        self.spinBox_MoveRobotTranslationalVelocity.setObjectName("spinBox_MoveRobotTranslationalVelocity")
        self.lineEdit_MoveRobotTranslationVelocity = QtWidgets.QLineEdit(MovementWindow)
        self.lineEdit_MoveRobotTranslationVelocity.setGeometry(QtCore.QRect(40, 110, 91, 22))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lineEdit_MoveRobotTranslationVelocity.setFont(font)
        self.lineEdit_MoveRobotTranslationVelocity.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lineEdit_MoveRobotTranslationVelocity.setObjectName("lineEdit_MoveRobotTranslationVelocity")
        self.line_8 = QtWidgets.QFrame(MovementWindow)
        self.line_8.setGeometry(QtCore.QRect(40, 270, 130, 31))
        self.line_8.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.pushButton_J2minus = QtWidgets.QPushButton(MovementWindow)
        self.pushButton_J2minus.setGeometry(QtCore.QRect(40, 390, 30, 30))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_J2minus.setFont(font)
        self.pushButton_J2minus.setObjectName("pushButton_J2minus")
        self.line_9 = QtWidgets.QFrame(MovementWindow)
        self.line_9.setGeometry(QtCore.QRect(51, 590, 130, 31))
        self.line_9.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.pushButton_J3minus = QtWidgets.QPushButton(MovementWindow)
        self.pushButton_J3minus.setGeometry(QtCore.QRect(40, 430, 30, 30))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_J3minus.setFont(font)
        self.pushButton_J3minus.setObjectName("pushButton_J3minus")
        self.pushButton_J1minus = QtWidgets.QPushButton(MovementWindow)
        self.pushButton_J1minus.setGeometry(QtCore.QRect(40, 350, 30, 30))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_J1minus.setFont(font)
        self.pushButton_J1minus.setObjectName("pushButton_J1minus")
        self.lineEdit_lineEdit_MoveRobotRotationalVelocity = QtWidgets.QLineEdit(MovementWindow)
        self.lineEdit_lineEdit_MoveRobotRotationalVelocity.setGeometry(QtCore.QRect(40, 310, 101, 22))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lineEdit_lineEdit_MoveRobotRotationalVelocity.setFont(font)
        self.lineEdit_lineEdit_MoveRobotRotationalVelocity.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lineEdit_lineEdit_MoveRobotRotationalVelocity.setObjectName("lineEdit_lineEdit_MoveRobotRotationalVelocity")
        self.spinBox_MoveRobotRotationalVelocity = QtWidgets.QSpinBox(MovementWindow)
        self.spinBox_MoveRobotRotationalVelocity.setGeometry(QtCore.QRect(150, 310, 42, 22))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.spinBox_MoveRobotRotationalVelocity.setFont(font)
        self.spinBox_MoveRobotRotationalVelocity.setObjectName("spinBox_MoveRobotRotationalVelocity")
        self.pushButton_J2plus = QtWidgets.QPushButton(MovementWindow)
        self.pushButton_J2plus.setGeometry(QtCore.QRect(80, 390, 30, 30))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_J2plus.setFont(font)
        self.pushButton_J2plus.setObjectName("pushButton_J2plus")
        self.pushButton_J3plus = QtWidgets.QPushButton(MovementWindow)
        self.pushButton_J3plus.setGeometry(QtCore.QRect(80, 430, 30, 30))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_J3plus.setFont(font)
        self.pushButton_J3plus.setObjectName("pushButton_J3plus")
        self.pushButton_J1plus = QtWidgets.QPushButton(MovementWindow)
        self.pushButton_J1plus.setGeometry(QtCore.QRect(80, 350, 30, 30))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_J1plus.setFont(font)
        self.pushButton_J1plus.setObjectName("pushButton_J1plus")
        # self.pushButton_J5plus = QtWidgets.QPushButton(MovementWindow)
        # self.pushButton_J5plus.setGeometry(QtCore.QRect(80, 510, 30, 30))
        # font = QtGui.QFont()
        # font.setPointSize(9)
        # self.pushButton_J5plus.setFont(font)
        # self.pushButton_J5plus.setObjectName("pushButton_J5plus")
        # self.pushButton_J6minus = QtWidgets.QPushButton(MovementWindow)
        # self.pushButton_J6minus.setGeometry(QtCore.QRect(40, 550, 30, 30))
        # font = QtGui.QFont()
        # font.setPointSize(9)
        # self.pushButton_J6minus.setFont(font)
        # self.pushButton_J6minus.setObjectName("pushButton_J6minus")
        # self.pushButton_J5minus = QtWidgets.QPushButton(MovementWindow)
        # self.pushButton_J5minus.setGeometry(QtCore.QRect(40, 510, 30, 30))
        # font = QtGui.QFont()
        # font.setPointSize(9)
        # self.pushButton_J5minus.setFont(font)
        # self.pushButton_J5minus.setObjectName("pushButton_J5minus")
        # self.pushButton_J4minus = QtWidgets.QPushButton(MovementWindow)
        # self.pushButton_J4minus.setGeometry(QtCore.QRect(40, 470, 30, 30))
        # font = QtGui.QFont()
        # font.setPointSize(9)
        # self.pushButton_J4minus.setFont(font)
        # self.pushButton_J4minus.setObjectName("pushButton_J4minus")
        # self.pushButton_J6plus = QtWidgets.QPushButton(MovementWindow)
        # self.pushButton_J6plus.setGeometry(QtCore.QRect(80, 550, 30, 30))
        # font = QtGui.QFont()
        # font.setPointSize(9)
        # self.pushButton_J6plus.setFont(font)
        # self.pushButton_J6plus.setObjectName("pushButton_J6plus")
        # self.pushButton_J4plus = QtWidgets.QPushButton(MovementWindow)
        # self.pushButton_J4plus.setGeometry(QtCore.QRect(80, 470, 30, 30))
        # font = QtGui.QFont()
        # font.setPointSize(9)
        # self.pushButton_J4plus.setFont(font)
        # self.pushButton_J4plus.setObjectName("pushButton_J4plus")
        self.pushButton_StartMoveRobotManually = QtWidgets.QPushButton(MovementWindow)
        self.pushButton_StartMoveRobotManually.setGeometry(QtCore.QRect(260, 142, 61, 41))
        font = QtGui.QFont()
        font.setFamily("abeatbyKai")
        font.setPointSize(9)
        self.pushButton_StartMoveRobotManually.setFont(font)
        self.pushButton_StartMoveRobotManually.setObjectName("pushButton_StartMoveRobotManually")
        self.pushButton_StopMoveRobotManually = QtWidgets.QPushButton(MovementWindow)
        self.pushButton_StopMoveRobotManually.setEnabled(False)
        self.pushButton_StopMoveRobotManually.setGeometry(QtCore.QRect(330, 142, 61, 41))
        font = QtGui.QFont()
        font.setFamily("abeatbyKai")
        font.setPointSize(9)
        self.pushButton_StopMoveRobotManually.setFont(font)
        self.pushButton_StopMoveRobotManually.setObjectName("pushButton_StopMoveRobotManually")
        self.lineEdit_MoveRobotManually = QtWidgets.QLineEdit(MovementWindow)
        self.lineEdit_MoveRobotManually.setGeometry(QtCore.QRect(270, 112, 111, 22))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lineEdit_MoveRobotManually.setFont(font)
        self.lineEdit_MoveRobotManually.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_MoveRobotManually.setObjectName("lineEdit_MoveRobotManually")
        self.lcdNumber_X = QtWidgets.QLCDNumber(MovementWindow)
        self.lcdNumber_X.setGeometry(QtCore.QRect(150, 150, 42, 30))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lcdNumber_X.setFont(font)
        self.lcdNumber_X.setObjectName("lcdNumber_X")
        self.lcdNumber_Y = QtWidgets.QLCDNumber(MovementWindow)
        self.lcdNumber_Y.setGeometry(QtCore.QRect(150, 190, 42, 30))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lcdNumber_Y.setFont(font)
        self.lcdNumber_Y.setObjectName("lcdNumber_Y")
        self.lcdNumber_Z = QtWidgets.QLCDNumber(MovementWindow)
        self.lcdNumber_Z.setGeometry(QtCore.QRect(150, 230, 42, 30))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lcdNumber_Z.setFont(font)
        self.lcdNumber_Z.setObjectName("lcdNumber_Z")
        self.lcdNumber_J1 = QtWidgets.QLCDNumber(MovementWindow)
        self.lcdNumber_J1.setGeometry(QtCore.QRect(150, 350, 42, 30))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lcdNumber_J1.setFont(font)
        self.lcdNumber_J1.setObjectName("lcdNumber_J1")
        self.lcdNumber_J2 = QtWidgets.QLCDNumber(MovementWindow)
        self.lcdNumber_J2.setGeometry(QtCore.QRect(150, 390, 42, 30))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lcdNumber_J2.setFont(font)
        self.lcdNumber_J2.setObjectName("lcdNumber_J2")
        self.lcdNumber_J3 = QtWidgets.QLCDNumber(MovementWindow)
        self.lcdNumber_J3.setGeometry(QtCore.QRect(150, 430, 42, 30))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lcdNumber_J3.setFont(font)
        self.lcdNumber_J3.setObjectName("lcdNumber_J3")
        # self.lcdNumber_J4 = QtWidgets.QLCDNumber(MovementWindow)
        # self.lcdNumber_J4.setGeometry(QtCore.QRect(150, 470, 42, 30))
        # font = QtGui.QFont()
        # font.setPointSize(9)
        # self.lcdNumber_J4.setFont(font)
        # self.lcdNumber_J4.setObjectName("lcdNumber_J4")
        # self.lcdNumber_J5 = QtWidgets.QLCDNumber(MovementWindow)
        # self.lcdNumber_J5.setGeometry(QtCore.QRect(150, 510, 42, 30))
        # font = QtGui.QFont()
        # font.setPointSize(9)
        # self.lcdNumber_J5.setFont(font)
        # self.lcdNumber_J5.setObjectName("lcdNumber_J5")
        # self.lcdNumber_J6 = QtWidgets.QLCDNumber(MovementWindow)
        # self.lcdNumber_J6.setGeometry(QtCore.QRect(150, 550, 42, 30))
        # font = QtGui.QFont()
        # font.setPointSize(9)
        # self.lcdNumber_J6.setFont(font)
        # self.lcdNumber_J6.setObjectName("lcdNumber_J6")
        # self.doubleSpin_Joint6_Value = QtWidgets.QDoubleSpinBox(MovementWindow)
        # self.doubleSpin_Joint6_Value.setGeometry(QtCore.QRect(351, 493, 61, 30))
        # font = QtGui.QFont()
        # font.setPointSize(9)
        # self.doubleSpin_Joint6_Value.setFont(font)
        # self.doubleSpin_Joint6_Value.setDecimals(3)
        # self.doubleSpin_Joint6_Value.setMinimum(-999.0)
        # self.doubleSpin_Joint6_Value.setMaximum(1000.0)
        # self.doubleSpin_Joint6_Value.setSingleStep(0.001)
        # self.doubleSpin_Joint6_Value.setObjectName("doubleSpin_Joint6_Value")
        # self.doubleSpin_Joint5_Value = QtWidgets.QDoubleSpinBox(MovementWindow)
        # self.doubleSpin_Joint5_Value.setGeometry(QtCore.QRect(351, 462, 61, 30))
        # font = QtGui.QFont()
        # font.setPointSize(9)
        # self.doubleSpin_Joint5_Value.setFont(font)
        # self.doubleSpin_Joint5_Value.setDecimals(3)
        # self.doubleSpin_Joint5_Value.setMinimum(-999.0)
        # self.doubleSpin_Joint5_Value.setMaximum(1000.0)
        # self.doubleSpin_Joint5_Value.setSingleStep(0.001)
        # self.doubleSpin_Joint5_Value.setObjectName("doubleSpin_Joint5_Value")
        self.doubleSpin_Joint3_Value = QtWidgets.QDoubleSpinBox(MovementWindow)
        self.doubleSpin_Joint3_Value.setGeometry(QtCore.QRect(351, 400, 61, 30))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.doubleSpin_Joint3_Value.setFont(font)
        self.doubleSpin_Joint3_Value.setDecimals(3)
        self.doubleSpin_Joint3_Value.setMinimum(-999.0)
        self.doubleSpin_Joint3_Value.setMaximum(1000.0)
        self.doubleSpin_Joint3_Value.setSingleStep(0.001)
        self.doubleSpin_Joint3_Value.setObjectName("doubleSpin_Joint3_Value")
        self.doubleSpin_Joint2_Value = QtWidgets.QDoubleSpinBox(MovementWindow)
        self.doubleSpin_Joint2_Value.setGeometry(QtCore.QRect(351, 369, 61, 30))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.doubleSpin_Joint2_Value.setFont(font)
        self.doubleSpin_Joint2_Value.setDecimals(3)
        self.doubleSpin_Joint2_Value.setMinimum(-999.0)
        self.doubleSpin_Joint2_Value.setMaximum(1000.0)
        self.doubleSpin_Joint2_Value.setSingleStep(0.001)
        self.doubleSpin_Joint2_Value.setObjectName("doubleSpin_Joint2_Value")
        self.doubleSpin_Joint1_Value = QtWidgets.QDoubleSpinBox(MovementWindow)
        self.doubleSpin_Joint1_Value.setGeometry(QtCore.QRect(351, 338, 61, 30))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.doubleSpin_Joint1_Value.setFont(font)
        self.doubleSpin_Joint1_Value.setDecimals(3)
        self.doubleSpin_Joint1_Value.setMinimum(-999.0)
        self.doubleSpin_Joint1_Value.setMaximum(1000.0)
        self.doubleSpin_Joint1_Value.setSingleStep(0.001)
        self.doubleSpin_Joint1_Value.setObjectName("doubleSpin_Joint1_Value")
        # self.doubleSpin_Joint4_Value = QtWidgets.QDoubleSpinBox(MovementWindow)
        # self.doubleSpin_Joint4_Value.setGeometry(QtCore.QRect(351, 431, 61, 30))
        # font = QtGui.QFont()
        # font.setPointSize(9)
        # self.doubleSpin_Joint4_Value.setFont(font)
        # self.doubleSpin_Joint4_Value.setDecimals(3)
        # self.doubleSpin_Joint4_Value.setMinimum(-999.0)
        # self.doubleSpin_Joint4_Value.setMaximum(1000.0)
        # self.doubleSpin_Joint4_Value.setSingleStep(0.001)
        # self.doubleSpin_Joint4_Value.setObjectName("doubleSpin_Joint4_Value")
        self.pushButton_Approach_Joint1 = QtWidgets.QPushButton(MovementWindow)
        self.pushButton_Approach_Joint1.setGeometry(QtCore.QRect(290, 337, 61, 32))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_Approach_Joint1.setFont(font)
        self.pushButton_Approach_Joint1.setObjectName("pushButton_Approach_Joint1")
        self.pushButton_Approach_Joint2 = QtWidgets.QPushButton(MovementWindow)
        self.pushButton_Approach_Joint2.setGeometry(QtCore.QRect(290, 368, 61, 32))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_Approach_Joint2.setFont(font)
        self.pushButton_Approach_Joint2.setObjectName("pushButton_Approach_Joint2")
        self.pushButton_Approach_Joint3 = QtWidgets.QPushButton(MovementWindow)
        self.pushButton_Approach_Joint3.setGeometry(QtCore.QRect(290, 399, 61, 32))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_Approach_Joint3.setFont(font)
        self.pushButton_Approach_Joint3.setObjectName("pushButton_Approach_Joint3")
        # self.pushButton_Approach_Joint6 = QtWidgets.QPushButton(MovementWindow)
        # self.pushButton_Approach_Joint6.setGeometry(QtCore.QRect(290, 492, 61, 32))
        # font = QtGui.QFont()
        # font.setPointSize(9)
        # self.pushButton_Approach_Joint6.setFont(font)
        # self.pushButton_Approach_Joint6.setObjectName("pushButton_Approach_Joint6")
        # self.pushButton_Approach_Joint5 = QtWidgets.QPushButton(MovementWindow)
        # self.pushButton_Approach_Joint5.setGeometry(QtCore.QRect(290, 461, 61, 32))
        # font = QtGui.QFont()
        # font.setPointSize(9)
        # self.pushButton_Approach_Joint5.setFont(font)
        # self.pushButton_Approach_Joint5.setObjectName("pushButton_Approach_Joint5")
        # self.pushButton_Approach_Joint4 = QtWidgets.QPushButton(MovementWindow)
        # self.pushButton_Approach_Joint4.setGeometry(QtCore.QRect(290, 430, 61, 32))
        # font = QtGui.QFont()
        # font.setPointSize(9)
        # self.pushButton_Approach_Joint4.setFont(font)
        # self.pushButton_Approach_Joint4.setObjectName("pushButton_Approach_Joint4")
        self.pushButton_ApproachAllJoint = QtWidgets.QPushButton(MovementWindow)
        self.pushButton_ApproachAllJoint.setGeometry(QtCore.QRect(240, 337, 41, 187))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_ApproachAllJoint.setFont(font)
        self.pushButton_ApproachAllJoint.setObjectName("pushButton_ApproachAllJoint")
        self.pushButton_EnableApproach = QtWidgets.QPushButton(MovementWindow)
        self.pushButton_EnableApproach.setGeometry(QtCore.QRect(240, 290, 171, 40))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_EnableApproach.setFont(font)
        self.pushButton_EnableApproach.setObjectName("pushButton_EnableApproach")
        self.line_10 = QtWidgets.QFrame(MovementWindow)
        self.line_10.setGeometry(QtCore.QRect(260, 190, 130, 31))
        self.line_10.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_10.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_10.setObjectName("line_10")
        self.line_11 = QtWidgets.QFrame(MovementWindow)
        self.line_11.setGeometry(QtCore.QRect(260, 590, 130, 31))
        self.line_11.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_11.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_11.setObjectName("line_11")
        self.line_7 = QtWidgets.QFrame(MovementWindow)
        self.line_7.setGeometry(QtCore.QRect(425, 109, 20, 481))
        self.line_7.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.line_12 = QtWidgets.QFrame(MovementWindow)
        self.line_12.setGeometry(QtCore.QRect(10, 100, 20, 481))
        self.line_12.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_12.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_12.setObjectName("line_12")
        self.lineEdit_MovTime = QtWidgets.QLineEdit(MovementWindow)
        self.lineEdit_MovTime.setGeometry(QtCore.QRect(463, 310, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lineEdit_MovTime.setFont(font)
        self.lineEdit_MovTime.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lineEdit_MovTime.setObjectName("lineEdit_MovTime")
        self.doubleSpinBox_MovTime = QtWidgets.QDoubleSpinBox(MovementWindow)
        self.doubleSpinBox_MovTime.setGeometry(QtCore.QRect(580, 310, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.doubleSpinBox_MovTime.setFont(font)
        self.doubleSpinBox_MovTime.setDecimals(1)
        self.doubleSpinBox_MovTime.setMaximum(99.0)
        self.doubleSpinBox_MovTime.setSingleStep(0.1)
        self.doubleSpinBox_MovTime.setProperty("value", 2.0)
        self.doubleSpinBox_MovTime.setObjectName("doubleSpinBox_MovTime")
        self.lineEdit_TypeOfExercise = QtWidgets.QLineEdit(MovementWindow)
        self.lineEdit_TypeOfExercise.setGeometry(QtCore.QRect(460, 113, 101, 22))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lineEdit_TypeOfExercise.setFont(font)
        self.lineEdit_TypeOfExercise.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lineEdit_TypeOfExercise.setObjectName("lineEdit_TypeOfExercise")
        self.radioButton_TypeOfExercise_Reaching = QtWidgets.QRadioButton(MovementWindow)
        self.radioButton_TypeOfExercise_Reaching.setGeometry(QtCore.QRect(464, 143, 82, 17))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.radioButton_TypeOfExercise_Reaching.setFont(font)
        self.radioButton_TypeOfExercise_Reaching.setChecked(False)
        self.radioButton_TypeOfExercise_Reaching.setObjectName("radioButton_TypeOfExercise_Reaching")
        self.buttonGroup = QtWidgets.QButtonGroup(MovementWindow)
        self.buttonGroup.setObjectName("buttonGroup")
        self.buttonGroup.addButton(self.radioButton_TypeOfExercise_Reaching)
        self.radioButton_TypeOfExercise_HandtoMouth = QtWidgets.QRadioButton(MovementWindow)
        self.radioButton_TypeOfExercise_HandtoMouth.setGeometry(QtCore.QRect(464, 163, 111, 17))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.radioButton_TypeOfExercise_HandtoMouth.setFont(font)
        self.radioButton_TypeOfExercise_HandtoMouth.setChecked(True)
        self.radioButton_TypeOfExercise_HandtoMouth.setObjectName("radioButton_TypeOfExercise_HandtoMouth")
        self.buttonGroup.addButton(self.radioButton_TypeOfExercise_HandtoMouth)
        self.radioButton_VelocityProfileBellshaped = QtWidgets.QRadioButton(MovementWindow)
        self.radioButton_VelocityProfileBellshaped.setGeometry(QtCore.QRect(675, 163, 91, 17))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.radioButton_VelocityProfileBellshaped.setFont(font)
        self.radioButton_VelocityProfileBellshaped.setChecked(True)
        self.radioButton_VelocityProfileBellshaped.setObjectName("radioButton_VelocityProfileBellshaped")
        self.buttonGroup_2 = QtWidgets.QButtonGroup(MovementWindow)
        self.buttonGroup_2.setObjectName("buttonGroup_2")
        self.buttonGroup_2.addButton(self.radioButton_VelocityProfileBellshaped)
        self.radioButton_VelocityProfileConstant = QtWidgets.QRadioButton(MovementWindow)
        self.radioButton_VelocityProfileConstant.setGeometry(QtCore.QRect(675, 143, 82, 17))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.radioButton_VelocityProfileConstant.setFont(font)
        self.radioButton_VelocityProfileConstant.setChecked(False)
        self.radioButton_VelocityProfileConstant.setObjectName("radioButton_VelocityProfileConstant")
        self.buttonGroup_2.addButton(self.radioButton_VelocityProfileConstant)
        self.lineEdit_TypeOfExercise_2 = QtWidgets.QLineEdit(MovementWindow)
        self.lineEdit_TypeOfExercise_2.setGeometry(QtCore.QRect(671, 113, 101, 22))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lineEdit_TypeOfExercise_2.setFont(font)
        self.lineEdit_TypeOfExercise_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lineEdit_TypeOfExercise_2.setObjectName("lineEdit_TypeOfExercise_2")
        self.lineEdit_MoveRobot_2 = QtWidgets.QLineEdit(MovementWindow)
        self.lineEdit_MoveRobot_2.setGeometry(QtCore.QRect(520, 60, 171, 23))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lineEdit_MoveRobot_2.setFont(font)
        self.lineEdit_MoveRobot_2.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_MoveRobot_2.setObjectName("lineEdit_MoveRobot_2")
        self.pushButton_SAVEMovement = QtWidgets.QPushButton(MovementWindow)
        self.pushButton_SAVEMovement.setEnabled(False)
        self.pushButton_SAVEMovement.setGeometry(QtCore.QRect(460, 426, 81, 40))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_SAVEMovement.setFont(font)
        self.pushButton_SAVEMovement.setObjectName("pushButton_SAVEMovement")
        self.pushButton_LOADMovement = QtWidgets.QPushButton(MovementWindow)
        self.pushButton_LOADMovement.setGeometry(QtCore.QRect(560, 350, 81, 40))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_LOADMovement.setFont(font)
        self.pushButton_LOADMovement.setObjectName("pushButton_LOADMovement")
        self.lineEdit = QtWidgets.QLineEdit(MovementWindow)
        self.lineEdit.setGeometry(QtCore.QRect(460, 501, 281, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lineEdit.setFont(font)
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        self.labelFileName_14 = QtWidgets.QLabel(MovementWindow)
        self.labelFileName_14.setGeometry(QtCore.QRect(460, 478, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.labelFileName_14.setFont(font)
        self.labelFileName_14.setAutoFillBackground(False)
        self.labelFileName_14.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.labelFileName_14.setFrameShape(QtWidgets.QFrame.Box)
        self.labelFileName_14.setObjectName("labelFileName_14")
        self.pushButton_GOtoTraining = QtWidgets.QPushButton(MovementWindow)
        self.pushButton_GOtoTraining.setEnabled(False)
        self.pushButton_GOtoTraining.setGeometry(QtCore.QRect(560, 540, 81, 40))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_GOtoTraining.setFont(font)
        self.pushButton_GOtoTraining.setObjectName("pushButton_GOtoTraining")
        self.line_13 = QtWidgets.QFrame(MovementWindow)
        self.line_13.setGeometry(QtCore.QRect(766, 110, 20, 481))
        self.line_13.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_13.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_13.setObjectName("line_13")
        self.line_14 = QtWidgets.QFrame(MovementWindow)
        self.line_14.setGeometry(QtCore.QRect(510, 590, 181, 31))
        self.line_14.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_14.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_14.setObjectName("line_14")
        self.lineEdit_lineEdit_MoveRobotRotationalVelocity_2 = QtWidgets.QLineEdit(MovementWindow)
        self.lineEdit_lineEdit_MoveRobotRotationalVelocity_2.setGeometry(QtCore.QRect(462, 193, 91, 22))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lineEdit_lineEdit_MoveRobotRotationalVelocity_2.setFont(font)
        self.lineEdit_lineEdit_MoveRobotRotationalVelocity_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lineEdit_lineEdit_MoveRobotRotationalVelocity_2.setObjectName("lineEdit_lineEdit_MoveRobotRotationalVelocity_2")
        self.lineEdit_lineEdit_MoveRobotRotationalVelocity_3 = QtWidgets.QLineEdit(MovementWindow)
        self.lineEdit_lineEdit_MoveRobotRotationalVelocity_3.setGeometry(QtCore.QRect(462, 253, 91, 22))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lineEdit_lineEdit_MoveRobotRotationalVelocity_3.setFont(font)
        self.lineEdit_lineEdit_MoveRobotRotationalVelocity_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lineEdit_lineEdit_MoveRobotRotationalVelocity_3.setObjectName("lineEdit_lineEdit_MoveRobotRotationalVelocity_3")
        self.lcdNumber_StartPos_X = QtWidgets.QLCDNumber(MovementWindow)
        self.lcdNumber_StartPos_X.setGeometry(QtCore.QRect(462, 215, 55, 25))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lcdNumber_StartPos_X.setFont(font)
        self.lcdNumber_StartPos_X.setDigitCount(4)
        self.lcdNumber_StartPos_X.setObjectName("lcdNumber_StartPos_X")
        self.lcdNumber_StartPos_Y = QtWidgets.QLCDNumber(MovementWindow)
        self.lcdNumber_StartPos_Y.setGeometry(QtCore.QRect(520, 215, 55, 25))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lcdNumber_StartPos_Y.setFont(font)
        self.lcdNumber_StartPos_Y.setDigitCount(4)
        self.lcdNumber_StartPos_Y.setObjectName("lcdNumber_StartPos_Y")
        self.lcdNumber_StartPos_Z = QtWidgets.QLCDNumber(MovementWindow)
        self.lcdNumber_StartPos_Z.setGeometry(QtCore.QRect(580, 215, 55, 25))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lcdNumber_StartPos_Z.setFont(font)
        self.lcdNumber_StartPos_Z.setDigitCount(4)
        self.lcdNumber_StartPos_Z.setObjectName("lcdNumber_StartPos_Z")
        self.lcdNumber_EndPos_Z = QtWidgets.QLCDNumber(MovementWindow)
        self.lcdNumber_EndPos_Z.setGeometry(QtCore.QRect(580, 275, 55, 25))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lcdNumber_EndPos_Z.setFont(font)
        self.lcdNumber_EndPos_Z.setDigitCount(4)
        self.lcdNumber_EndPos_Z.setObjectName("lcdNumber_EndPos_Z")
        self.lcdNumber_EndPos_X = QtWidgets.QLCDNumber(MovementWindow)
        self.lcdNumber_EndPos_X.setGeometry(QtCore.QRect(462, 275, 55, 25))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lcdNumber_EndPos_X.setFont(font)
        self.lcdNumber_EndPos_X.setDigitCount(4)
        self.lcdNumber_EndPos_X.setObjectName("lcdNumber_EndPos_X")
        self.lcdNumber_EndPos_Y = QtWidgets.QLCDNumber(MovementWindow)
        self.lcdNumber_EndPos_Y.setGeometry(QtCore.QRect(520, 275, 55, 25))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lcdNumber_EndPos_Y.setFont(font)
        self.lcdNumber_EndPos_Y.setDigitCount(4)
        self.lcdNumber_EndPos_Y.setObjectName("lcdNumber_EndPos_Y")
        self.radioButton_SideRight = QtWidgets.QRadioButton(MovementWindow)
        self.radioButton_SideRight.setGeometry(QtCore.QRect(576, 163, 91, 17))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.radioButton_SideRight.setFont(font)
        self.radioButton_SideRight.setChecked(True)
        self.radioButton_SideRight.setObjectName("radioButton_SideRight")
        self.lineEdit_Side = QtWidgets.QLineEdit(MovementWindow)
        self.lineEdit_Side.setGeometry(QtCore.QRect(572, 113, 91, 22))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lineEdit_Side.setFont(font)
        self.lineEdit_Side.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lineEdit_Side.setObjectName("lineEdit_Side")
        self.radioButton_SideLeft = QtWidgets.QRadioButton(MovementWindow)
        self.radioButton_SideLeft.setGeometry(QtCore.QRect(576, 143, 82, 17))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.radioButton_SideLeft.setFont(font)
        self.radioButton_SideLeft.setChecked(False)
        self.radioButton_SideLeft.setObjectName("radioButton_SideLeft")
        self.pushButton_SetCurrentPos_1 = QtWidgets.QPushButton(MovementWindow)
        self.pushButton_SetCurrentPos_1.setGeometry(QtCore.QRect(640, 211, 75, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_SetCurrentPos_1.setFont(font)
        self.pushButton_SetCurrentPos_1.setObjectName("pushButton_SetCurrentPos_1")
        self.pushButton_SetCurrentPos_2 = QtWidgets.QPushButton(MovementWindow)
        self.pushButton_SetCurrentPos_2.setGeometry(QtCore.QRect(640, 272, 75, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_SetCurrentPos_2.setFont(font)
        self.pushButton_SetCurrentPos_2.setObjectName("pushButton_SetCurrentPos_2")
        self.pushButton_CREATEMovement = QtWidgets.QPushButton(MovementWindow)
        self.pushButton_CREATEMovement.setGeometry(QtCore.QRect(460, 350, 81, 40))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_CREATEMovement.setFont(font)
        self.pushButton_CREATEMovement.setObjectName("pushButton_CREATEMovement")
        self.line_15 = QtWidgets.QFrame(MovementWindow)
        self.line_15.setGeometry(QtCore.QRect(510, 390, 181, 31))
        self.line_15.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_15.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_15.setObjectName("line_15")

        self.retranslateUi(MovementWindow)
        QtCore.QMetaObject.connectSlotsByName(MovementWindow)
        MovementWindow.setTabOrder(self.lineEdit_MoveRobot, self.lineEdit_MoveRobotTranslationVelocity)
        MovementWindow.setTabOrder(self.lineEdit_MoveRobotTranslationVelocity, self.spinBox_MoveRobotTranslationalVelocity)
        MovementWindow.setTabOrder(self.spinBox_MoveRobotTranslationalVelocity, self.pushButton_Xminus)
        MovementWindow.setTabOrder(self.pushButton_Xminus, self.pushButton_Xplus)
        MovementWindow.setTabOrder(self.pushButton_Xplus, self.pushButton_Yminus)
        MovementWindow.setTabOrder(self.pushButton_Yminus, self.pushButton_Yplus)
        MovementWindow.setTabOrder(self.pushButton_Yplus, self.pushButton_Zminus)
        MovementWindow.setTabOrder(self.pushButton_Zminus, self.pushButton_Zplus)
        MovementWindow.setTabOrder(self.pushButton_Zplus, self.lineEdit_lineEdit_MoveRobotRotationalVelocity)
        MovementWindow.setTabOrder(self.lineEdit_lineEdit_MoveRobotRotationalVelocity, self.spinBox_MoveRobotRotationalVelocity)
        MovementWindow.setTabOrder(self.spinBox_MoveRobotRotationalVelocity, self.pushButton_J1minus)
        MovementWindow.setTabOrder(self.pushButton_J1minus, self.pushButton_J1plus)
        MovementWindow.setTabOrder(self.pushButton_J1plus, self.pushButton_J2minus)
        MovementWindow.setTabOrder(self.pushButton_J2minus, self.pushButton_J2plus)
        MovementWindow.setTabOrder(self.pushButton_J2plus, self.pushButton_J3minus)
        MovementWindow.setTabOrder(self.pushButton_J3minus, self.pushButton_J3plus)
        MovementWindow.setTabOrder(self.pushButton_J3plus, self.lineEdit_MoveRobotManually)
        # MovementWindow.setTabOrder(self.pushButton_J3plus, self.pushButton_J4minus)
        # MovementWindow.setTabOrder(self.pushButton_J4minus, self.pushButton_J4plus)
        # MovementWindow.setTabOrder(self.pushButton_J4plus, self.pushButton_J5minus)
        # MovementWindow.setTabOrder(self.pushButton_J5minus, self.pushButton_J5plus)
        # MovementWindow.setTabOrder(self.pushButton_J5plus, self.pushButton_J6minus)
        # MovementWindow.setTabOrder(self.pushButton_J6minus, self.pushButton_J6plus)
        # MovementWindow.setTabOrder(self.pushButton_J6plus, self.lineEdit_MoveRobotManually)
        MovementWindow.setTabOrder(self.lineEdit_MoveRobotManually, self.pushButton_StartMoveRobotManually)
        MovementWindow.setTabOrder(self.pushButton_StartMoveRobotManually, self.pushButton_StopMoveRobotManually)
        MovementWindow.setTabOrder(self.pushButton_StopMoveRobotManually, self.pushButton_LoadJointPosition)
        MovementWindow.setTabOrder(self.pushButton_LoadJointPosition, self.pushButton_EnableApproach)
        MovementWindow.setTabOrder(self.pushButton_EnableApproach, self.pushButton_ApproachAllJoint)
        MovementWindow.setTabOrder(self.pushButton_ApproachAllJoint, self.pushButton_Approach_Joint1)
        MovementWindow.setTabOrder(self.pushButton_Approach_Joint1, self.doubleSpin_Joint1_Value)
        MovementWindow.setTabOrder(self.doubleSpin_Joint1_Value, self.pushButton_Approach_Joint2)
        MovementWindow.setTabOrder(self.pushButton_Approach_Joint2, self.doubleSpin_Joint2_Value)
        MovementWindow.setTabOrder(self.doubleSpin_Joint2_Value, self.pushButton_Approach_Joint3)
        MovementWindow.setTabOrder(self.pushButton_Approach_Joint3, self.doubleSpin_Joint3_Value)
        MovementWindow.setTabOrder(self.doubleSpin_Joint3_Value, self.pushButton_SaveStartPosition)
        # MovementWindow.setTabOrder(self.doubleSpin_Joint3_Value, self.pushButton_Approach_Joint4)
        # MovementWindow.setTabOrder(self.pushButton_Approach_Joint4, self.doubleSpin_Joint4_Value)
        # MovementWindow.setTabOrder(self.doubleSpin_Joint4_Value, self.pushButton_Approach_Joint5)
        # MovementWindow.setTabOrder(self.pushButton_Approach_Joint5, self.doubleSpin_Joint5_Value)
        # MovementWindow.setTabOrder(self.doubleSpin_Joint5_Value, self.pushButton_Approach_Joint6)
        # MovementWindow.setTabOrder(self.pushButton_Approach_Joint6, self.doubleSpin_Joint6_Value)
        # MovementWindow.setTabOrder(self.doubleSpin_Joint6_Value, self.pushButton_SaveStartPosition)
        MovementWindow.setTabOrder(self.pushButton_SaveStartPosition, self.lineEdit_MovTime)
        MovementWindow.setTabOrder(self.lineEdit_MovTime, self.doubleSpinBox_MovTime)
        MovementWindow.setTabOrder(self.doubleSpinBox_MovTime, self.lineEdit_TypeOfExercise)
        MovementWindow.setTabOrder(self.lineEdit_TypeOfExercise, self.radioButton_TypeOfExercise_Reaching)
        MovementWindow.setTabOrder(self.radioButton_TypeOfExercise_Reaching, self.radioButton_TypeOfExercise_HandtoMouth)

    def retranslateUi(self, MovementWindow):
        _translate = QtCore.QCoreApplication.translate
        MovementWindow.setWindowTitle(_translate("MovementWindow", "Dialog"))
        self.pushButton_SaveStartPosition.setText(_translate("MovementWindow", "SAVE position"))
        self.pushButton_LoadJointPosition.setText(_translate("MovementWindow", "LOAD  Position"))
        self.pushButton_Xminus.setText(_translate("MovementWindow", "X-"))
        self.pushButton_Xplus.setText(_translate("MovementWindow", "X+"))
        self.lineEdit_MoveRobot.setText(_translate("MovementWindow", "MOVE THE ROBOT TO DEFINED POSITION"))
        self.pushButton_Yminus.setText(_translate("MovementWindow", "Y-"))
        self.pushButton_Yplus.setText(_translate("MovementWindow", "Y+"))
        self.pushButton_Zminus.setText(_translate("MovementWindow", "Z-"))
        self.pushButton_Zplus.setText(_translate("MovementWindow", "Z+"))
        self.lineEdit_MoveRobotTranslationVelocity.setText(_translate("MovementWindow", "Position (cm)"))
        self.pushButton_J2minus.setText(_translate("MovementWindow", "J2-"))
        self.pushButton_J3minus.setText(_translate("MovementWindow", "J3-"))
        self.pushButton_J1minus.setText(_translate("MovementWindow", "J1-"))
        self.lineEdit_lineEdit_MoveRobotRotationalVelocity.setText(_translate("MovementWindow", "Velocity (deg/s)"))
        self.pushButton_J2plus.setText(_translate("MovementWindow", "J2+"))
        self.pushButton_J3plus.setText(_translate("MovementWindow", "J3+"))
        self.pushButton_J1plus.setText(_translate("MovementWindow", "J1+"))
        # self.pushButton_J5plus.setText(_translate("MovementWindow", "J5+"))
        # self.pushButton_J6minus.setText(_translate("MovementWindow", "J6-"))
        # self.pushButton_J5minus.setText(_translate("MovementWindow", "J5+"))
        # self.pushButton_J4minus.setText(_translate("MovementWindow", "J4-"))
        # self.pushButton_J6plus.setText(_translate("MovementWindow", "J6+"))
        # self.pushButton_J4plus.setText(_translate("MovementWindow", "J4+"))
        self.pushButton_StartMoveRobotManually.setText(_translate("MovementWindow", "START "))
        self.pushButton_StopMoveRobotManually.setText(_translate("MovementWindow", "STOP"))
        self.lineEdit_MoveRobotManually.setText(_translate("MovementWindow", "MOVE MANUALLY"))
        self.pushButton_Approach_Joint1.setText(_translate("MovementWindow", "J1"))
        self.pushButton_Approach_Joint2.setText(_translate("MovementWindow", "J2"))
        self.pushButton_Approach_Joint3.setText(_translate("MovementWindow", "J3"))
        # self.pushButton_Approach_Joint6.setText(_translate("MovementWindow", "J6"))
        # self.pushButton_Approach_Joint5.setText(_translate("MovementWindow", "J5"))
        # self.pushButton_Approach_Joint4.setText(_translate("MovementWindow", "J4"))
        self.pushButton_ApproachAllJoint.setText(_translate("MovementWindow", "\n"
" A \n"
" p \n"
" p \n"
" r \n"
" o \n"
" a \n"
" c \n"
" h \n"
" \n"
" A \n"
" L \n"
" L  \n"
""))
        self.pushButton_EnableApproach.setText(_translate("MovementWindow", "Enable approach"))
        self.lineEdit_MovTime.setText(_translate("MovementWindow", "Movement Time"))
        self.lineEdit_TypeOfExercise.setText(_translate("MovementWindow", "Type of exercise"))
        self.radioButton_TypeOfExercise_Reaching.setText(_translate("MovementWindow", "Reaching"))
        self.radioButton_TypeOfExercise_HandtoMouth.setText(_translate("MovementWindow", "Hand to mouth"))
        self.radioButton_VelocityProfileBellshaped.setText(_translate("MovementWindow", "Bell shaped"))
        self.radioButton_VelocityProfileConstant.setText(_translate("MovementWindow", "Constant"))
        self.lineEdit_TypeOfExercise_2.setText(_translate("MovementWindow", "Velocity profile"))
        self.lineEdit_MoveRobot_2.setText(_translate("MovementWindow", "CREATE MOVEMENT"))
        self.pushButton_SAVEMovement.setText(_translate("MovementWindow", "SAVE AS\n"
"  movement"))
        self.pushButton_LOADMovement.setText(_translate("MovementWindow", "LOAD \n"
"  movement"))
        self.labelFileName_14.setText(_translate("MovementWindow", "Movement  NAME"))
        self.pushButton_GOtoTraining.setText(_translate("MovementWindow", "Go to \n"
" TRAINING"))
        self.lineEdit_lineEdit_MoveRobotRotationalVelocity_2.setText(_translate("MovementWindow", "START Position"))
        self.lineEdit_lineEdit_MoveRobotRotationalVelocity_3.setText(_translate("MovementWindow", "END Position"))
        self.radioButton_SideRight.setText(_translate("MovementWindow", "Right"))
        self.lineEdit_Side.setText(_translate("MovementWindow", "Side"))
        self.radioButton_SideLeft.setText(_translate("MovementWindow", "Left"))
        self.pushButton_SetCurrentPos_1.setText(_translate("MovementWindow", "Set current\n"
" Position"))
        self.pushButton_SetCurrentPos_2.setText(_translate("MovementWindow", "Set current\n"
" Position"))
        self.pushButton_CREATEMovement.setText(_translate("MovementWindow", "CREATE \n"
"  movement"))


def main():
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MovementWindow = QtWidgets.QDialog()
    ui = Ui_MovementWindow()
    ui.setupUi(MovementWindow)
    MovementWindow.show()
    sys.exit(app.exec_())


if __name__ == "__main__":
    main()