# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'rehab_gui/rehab_gui/ui/FMRRMainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FMRRMainWindow(object):
    def setupUi(self, FMRRMainWindow):
        FMRRMainWindow.setObjectName("FMRRMainWindow")
        FMRRMainWindow.resize(600, 900)
        self.tabWidget = QtWidgets.QTabWidget(FMRRMainWindow)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 600, 600))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.tabWidget.setFont(font)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setIconSize(QtCore.QSize(160, 16))
        self.tabWidget.setObjectName("tabWidget")
        self.tabRobotMovement = QtWidgets.QWidget()
        self.tabRobotMovement.setObjectName("tabRobotMovement")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.tabRobotMovement)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(10, 0, 611, 551))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_RobotMovement = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_RobotMovement.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_RobotMovement.setObjectName("verticalLayout_RobotMovement")
        self.tabWidget.addTab(self.tabRobotMovement, "")
        self.tabRehabilitationMovement = QtWidgets.QWidget()
        self.tabRehabilitationMovement.setObjectName("tabRehabilitationMovement")
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.tabRehabilitationMovement)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(10, 0, 611, 561))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_RehabilitationMovement = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_RehabilitationMovement.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_RehabilitationMovement.setObjectName("verticalLayout_RehabilitationMovement")
        self.tabWidget.addTab(self.tabRehabilitationMovement, "")
        self.tabTrainingProtocol = QtWidgets.QWidget()
        self.tabTrainingProtocol.setObjectName("tabTrainingProtocol")
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(self.tabTrainingProtocol)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(0, 0, 611, 561))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.verticalLayout_TrainingProtocol = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.verticalLayout_TrainingProtocol.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_TrainingProtocol.setObjectName("verticalLayout_TrainingProtocol")
        self.tabWidget.addTab(self.tabTrainingProtocol, "")
        self.tabOnlineViewer = QtWidgets.QWidget()
        self.tabOnlineViewer.setObjectName("tabOnlineViewer")
        self.graphicsView = QtWidgets.QGraphicsView(self.tabOnlineViewer)
        self.graphicsView.setGeometry(QtCore.QRect(0, 10, 591, 491))
        self.graphicsView.setObjectName("graphicsView")
        self.tabWidget.addTab(self.tabOnlineViewer, "")
        self.verticalLayoutWidget = QtWidgets.QWidget(FMRRMainWindow)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 610, 601, 261))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_MotorsManagement = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_MotorsManagement.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_MotorsManagement.setObjectName("verticalLayout_MotorsManagement")
        self.pushButton_CloseProgram = QtWidgets.QPushButton(FMRRMainWindow)
        self.pushButton_CloseProgram.setGeometry(QtCore.QRect(500, 870, 80, 25))
        icon = QtGui.QIcon.fromTheme("application-exit")
        self.pushButton_CloseProgram.setIcon(icon)
        self.pushButton_CloseProgram.setAutoDefault(True)
        self.pushButton_CloseProgram.setDefault(True)
        self.pushButton_CloseProgram.setFlat(False)
        self.pushButton_CloseProgram.setObjectName("pushButton_CloseProgram")

        self.retranslateUi(FMRRMainWindow)
        self.tabWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(FMRRMainWindow)

    def retranslateUi(self, FMRRMainWindow):
        _translate = QtCore.QCoreApplication.translate
        FMRRMainWindow.setWindowTitle(_translate("FMRRMainWindow", "Dialog"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabRobotMovement), _translate("FMRRMainWindow", "Robot Movement"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabRehabilitationMovement), _translate("FMRRMainWindow", "Rehabilitation Movement"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabTrainingProtocol), _translate("FMRRMainWindow", "Training Protocol"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabOnlineViewer), _translate("FMRRMainWindow", "Online Data Viewer"))
        self.pushButton_CloseProgram.setText(_translate("FMRRMainWindow", "Exit"))
