# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'TrainingProtocolWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TrainingProtocolWindow(object):
    def setupUi(self, TrainingProtocolWindow):
        TrainingProtocolWindow.setObjectName("TrainingProtocolWindow")
        TrainingProtocolWindow.resize(885, 723)
        font = QtGui.QFont()
        font.setFamily("FreeSans")
        font.setPointSize(9)
        font.setKerning(False)
        TrainingProtocolWindow.setFont(font)

        # Main vertical layout applied directly to the dialog
        self.verticalLayout = QtWidgets.QVBoxLayout(TrainingProtocolWindow)
        self.verticalLayout.setObjectName("verticalLayout")

        # Row 1: Exercise type / Side / Mode selectors
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_4 = QtWidgets.QLabel(TrainingProtocolWindow)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout.addWidget(self.label_4)
        self.radioButton_TypeOfExercise_Reaching = QtWidgets.QRadioButton(TrainingProtocolWindow)
        self.radioButton_TypeOfExercise_Reaching.setChecked(False)
        self.radioButton_TypeOfExercise_Reaching.setObjectName("radioButton_TypeOfExercise_Reaching")
        self.horizontalLayout.addWidget(self.radioButton_TypeOfExercise_Reaching)
        self.radioButton_TypeOfExercise_HandtoMouth = QtWidgets.QRadioButton(TrainingProtocolWindow)
        self.radioButton_TypeOfExercise_HandtoMouth.setChecked(False)
        self.radioButton_TypeOfExercise_HandtoMouth.setObjectName("radioButton_TypeOfExercise_HandtoMouth")
        self.horizontalLayout.addWidget(self.radioButton_TypeOfExercise_HandtoMouth)
        spacerItem = QtWidgets.QSpacerItem(15, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.label_5 = QtWidgets.QLabel(TrainingProtocolWindow)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout.addWidget(self.label_5)
        self.radioButton_SideLeft = QtWidgets.QRadioButton(TrainingProtocolWindow)
        self.radioButton_SideLeft.setChecked(False)
        self.radioButton_SideLeft.setObjectName("radioButton_SideLeft")
        self.horizontalLayout.addWidget(self.radioButton_SideLeft)
        self.radioButton_SideRight = QtWidgets.QRadioButton(TrainingProtocolWindow)
        self.radioButton_SideRight.setObjectName("radioButton_SideRight")
        self.horizontalLayout.addWidget(self.radioButton_SideRight)
        spacerItem1 = QtWidgets.QSpacerItem(13, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.label_3 = QtWidgets.QLabel(TrainingProtocolWindow)
        fontMode = QtGui.QFont()
        fontMode.setFamily("FreeSans")
        fontMode.setPointSize(8)
        fontMode.setBold(False)
        fontMode.setKerning(False)
        self.label_3.setFont(fontMode)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.radioButton_RehabMode = QtWidgets.QRadioButton(TrainingProtocolWindow)
        self.radioButton_RehabMode.setObjectName("radioButton_RehabMode")
        self.horizontalLayout.addWidget(self.radioButton_RehabMode)
        self.radioButton_EEGMode = QtWidgets.QRadioButton(TrainingProtocolWindow)
        self.radioButton_EEGMode.setObjectName("radioButton_EEGMode")
        self.horizontalLayout.addWidget(self.radioButton_EEGMode)
        self.verticalLayout.addLayout(self.horizontalLayout)

        # Row 2: 20-phase grid
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")

        def _spinbox():
            sb = QtWidgets.QSpinBox(TrainingProtocolWindow)
            sp = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
            sp.setHorizontalStretch(0)
            sp.setVerticalStretch(0)
            sp.setHeightForWidth(sb.sizePolicy().hasHeightForWidth())
            sb.setSizePolicy(sp)
            sb.setMinimumSize(QtCore.QSize(8, 8))
            sb.setMaximumSize(QtCore.QSize(40, 30))
            sb.setMaximum(100)
            return sb

        def _progressbar():
            pb = QtWidgets.QProgressBar(TrainingProtocolWindow)
            pb.setProperty("value", 24)
            return pb

        def _lcd():
            lcd = QtWidgets.QLCDNumber(TrainingProtocolWindow)
            lcd.setDigitCount(3)
            return lcd

        self.label = QtWidgets.QLabel(TrainingProtocolWindow)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 4)
        self.label_2 = QtWidgets.QLabel(TrainingProtocolWindow)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 4, 1, 4)

        phases_left = [
            ("01", 2), ("02", 3), ("03", 4), ("04", 5), ("05", 6),
            ("06", 7), ("07", 8), ("08", 9), ("09", 10), ("10", 11),
        ]
        phases_right = [
            ("11", 2), ("12", 3), ("13", 4), ("14", 5), ("15", 6),
            ("16", 7), ("17", 8), ("18", 9), ("19", 10), ("20", 11),
        ]

        for num, row in phases_left:
            pb = _progressbar()
            pb.setObjectName("progressBarPhase" + num)
            self.gridLayout.addWidget(pb, row, 0, 1, 1)
            setattr(self, "progressBarPhase" + num, pb)
            sd = _spinbox()
            sd.setObjectName("spinBoxDurationPhase" + num)
            self.gridLayout.addWidget(sd, row, 1, 1, 1)
            setattr(self, "spinBoxDurationPhase" + num, sd)
            sp = _spinbox()
            sp.setObjectName("spinBoxPercPhase" + num)
            self.gridLayout.addWidget(sp, row, 2, 1, 1)
            setattr(self, "spinBoxPercPhase" + num, sp)
            lc = _lcd()
            lc.setObjectName("lcdNumberMaxVelPhase" + num)
            self.gridLayout.addWidget(lc, row, 3, 1, 1)
            setattr(self, "lcdNumberMaxVelPhase" + num, lc)

        for num, row in phases_right:
            pb = _progressbar()
            pb.setObjectName("progressBarPhase" + num)
            self.gridLayout.addWidget(pb, row, 4, 1, 1)
            setattr(self, "progressBarPhase" + num, pb)
            sd = _spinbox()
            sd.setObjectName("spinBoxDurationPhase" + num)
            self.gridLayout.addWidget(sd, row, 5, 1, 1)
            setattr(self, "spinBoxDurationPhase" + num, sd)
            sp = _spinbox()
            sp.setObjectName("spinBoxPercPhase" + num)
            self.gridLayout.addWidget(sp, row, 6, 1, 1)
            setattr(self, "spinBoxPercPhase" + num, sp)
            lc = _lcd()
            lc.setObjectName("lcdNumberMaxVelPhase" + num)
            self.gridLayout.addWidget(lc, row, 7, 1, 1)
            setattr(self, "lcdNumberMaxVelPhase" + num, lc)

        self.verticalLayout.addLayout(self.gridLayout)

        # Row 3: Live status LCD numbers
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_6 = QtWidgets.QLabel(TrainingProtocolWindow)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_2.addWidget(self.label_6)
        self.lcdNumber_MaxVel = QtWidgets.QLCDNumber(TrainingProtocolWindow)
        self.lcdNumber_MaxVel.setObjectName("lcdNumber_MaxVel")
        self.horizontalLayout_2.addWidget(self.lcdNumber_MaxVel)
        self.label_7 = QtWidgets.QLabel(TrainingProtocolWindow)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_2.addWidget(self.label_7)
        self.lcdNumber_SinglePhaseDuration = QtWidgets.QLCDNumber(TrainingProtocolWindow)
        self.lcdNumber_SinglePhaseDuration.setObjectName("lcdNumber_SinglePhaseDuration")
        self.horizontalLayout_2.addWidget(self.lcdNumber_SinglePhaseDuration)
        self.label_8 = QtWidgets.QLabel(TrainingProtocolWindow)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_2.addWidget(self.label_8)
        self.lcdNumberExerciseTotalTime = QtWidgets.QLCDNumber(TrainingProtocolWindow)
        self.lcdNumberExerciseTotalTime.setDigitCount(2)
        self.lcdNumberExerciseTotalTime.setObjectName("lcdNumberExerciseTotalTime")
        self.horizontalLayout_2.addWidget(self.lcdNumberExerciseTotalTime)
        self.label_9 = QtWidgets.QLabel(TrainingProtocolWindow)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_2.addWidget(self.label_9)
        self.lcdNumber_MovementCOUNT = QtWidgets.QLCDNumber(TrainingProtocolWindow)
        self.lcdNumber_MovementCOUNT.setDigitCount(3)
        self.lcdNumber_MovementCOUNT.setObjectName("lcdNumber_MovementCOUNT")
        self.horizontalLayout_2.addWidget(self.lcdNumber_MovementCOUNT)
        self.verticalLayout.addLayout(self.horizontalLayout_2)

        # Row 4: Control buttons
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.pushButton_LoadCreateProtocol = QtWidgets.QPushButton(TrainingProtocolWindow)
        self.pushButton_LoadCreateProtocol.setEnabled(True)
        spLoad = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        spLoad.setHorizontalStretch(0)
        spLoad.setVerticalStretch(0)
        spLoad.setHeightForWidth(self.pushButton_LoadCreateProtocol.sizePolicy().hasHeightForWidth())
        self.pushButton_LoadCreateProtocol.setSizePolicy(spLoad)
        self.pushButton_LoadCreateProtocol.setObjectName("pushButton_LoadCreateProtocol")
        self.gridLayout_2.addWidget(self.pushButton_LoadCreateProtocol, 0, 0, 1, 1)
        self.pushButton_SaveProtocol = QtWidgets.QPushButton(TrainingProtocolWindow)
        self.pushButton_SaveProtocol.setObjectName("pushButton_SaveProtocol")
        self.gridLayout_2.addWidget(self.pushButton_SaveProtocol, 1, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(TrainingProtocolWindow)
        self.label_10.setObjectName("label_10")
        self.gridLayout_2.addWidget(self.label_10, 0, 2, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(TrainingProtocolWindow)
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout_2.addWidget(self.lineEdit, 1, 2, 1, 1)
        fontBold = QtGui.QFont()
        fontBold.setFamily("FreeSans")
        fontBold.setPointSize(9)
        fontBold.setBold(True)
        fontBold.setKerning(False)
        self.pushButton_STARTtrainig = QtWidgets.QPushButton(TrainingProtocolWindow)
        self.pushButton_STARTtrainig.setEnabled(False)
        spStart = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        spStart.setHorizontalStretch(0)
        spStart.setVerticalStretch(0)
        spStart.setHeightForWidth(self.pushButton_STARTtrainig.sizePolicy().hasHeightForWidth())
        self.pushButton_STARTtrainig.setSizePolicy(spStart)
        self.pushButton_STARTtrainig.setFont(fontBold)
        self.pushButton_STARTtrainig.setObjectName("pushButton_STARTtrainig")
        self.gridLayout_2.addWidget(self.pushButton_STARTtrainig, 0, 3, 2, 1)
        self.pushButton_PauseTrainig = QtWidgets.QPushButton(TrainingProtocolWindow)
        self.pushButton_PauseTrainig.setEnabled(False)
        spPause = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        spPause.setHorizontalStretch(0)
        spPause.setVerticalStretch(0)
        spPause.setHeightForWidth(self.pushButton_PauseTrainig.sizePolicy().hasHeightForWidth())
        self.pushButton_PauseTrainig.setSizePolicy(spPause)
        self.pushButton_PauseTrainig.setFont(fontBold)
        self.pushButton_PauseTrainig.setObjectName("pushButton_PauseTrainig")
        self.gridLayout_2.addWidget(self.pushButton_PauseTrainig, 0, 4, 1, 1)
        self.pushButton_ResumeTraining = QtWidgets.QPushButton(TrainingProtocolWindow)
        self.pushButton_ResumeTraining.setEnabled(False)
        spResume = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        spResume.setHorizontalStretch(0)
        spResume.setVerticalStretch(0)
        spResume.setHeightForWidth(self.pushButton_ResumeTraining.sizePolicy().hasHeightForWidth())
        self.pushButton_ResumeTraining.setSizePolicy(spResume)
        self.pushButton_ResumeTraining.setFont(fontBold)
        self.pushButton_ResumeTraining.setObjectName("pushButton_ResumeTraining")
        self.gridLayout_2.addWidget(self.pushButton_ResumeTraining, 1, 4, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_2)

        self.retranslateUi(TrainingProtocolWindow)
        QtCore.QMetaObject.connectSlotsByName(TrainingProtocolWindow)

    def retranslateUi(self, TrainingProtocolWindow):
        _translate = QtCore.QCoreApplication.translate
        TrainingProtocolWindow.setWindowTitle(_translate("TrainingProtocolWindow", "Dialog"))
        self.label_4.setText(_translate("TrainingProtocolWindow", "Exercise"))
        self.radioButton_TypeOfExercise_Reaching.setText(_translate("TrainingProtocolWindow", "Reaching"))
        self.radioButton_TypeOfExercise_HandtoMouth.setText(_translate("TrainingProtocolWindow", "Hand to mouth"))
        self.label_5.setText(_translate("TrainingProtocolWindow", "Side"))
        self.radioButton_SideLeft.setText(_translate("TrainingProtocolWindow", "Left"))
        self.radioButton_SideRight.setText(_translate("TrainingProtocolWindow", "Right"))
        self.label_3.setText(_translate("TrainingProtocolWindow", "Mode"))
        self.radioButton_RehabMode.setText(_translate("TrainingProtocolWindow", "rehab"))
        self.radioButton_EEGMode.setText(_translate("TrainingProtocolWindow", "eeg"))
        self.label_6.setText(_translate("TrainingProtocolWindow", "Vmax (cm/s)"))
        self.label_7.setText(_translate("TrainingProtocolWindow", "Mov T(s)"))
        self.label_8.setText(_translate("TrainingProtocolWindow", "Exercise T(s)"))
        self.label_9.setText(_translate("TrainingProtocolWindow", "Mov CNT"))
        self.label_2.setText(_translate("TrainingProtocolWindow", "  Perc                                 Duration   Ovr  cm/s"))
        self.label.setText(_translate("TrainingProtocolWindow", "  Perc                                 Duration   Ovr  cm/s"))
        self.pushButton_STARTtrainig.setText(_translate("TrainingProtocolWindow", "START \n"
" Training"))
        self.pushButton_ResumeTraining.setText(_translate("TrainingProtocolWindow", "RESUME \n"
" Training"))
        self.pushButton_PauseTrainig.setText(_translate("TrainingProtocolWindow", "PAUSE \n"
" Training"))
        self.label_10.setText(_translate("TrainingProtocolWindow", "Movement \n"
" NAME"))
        self.pushButton_LoadCreateProtocol.setText(_translate("TrainingProtocolWindow", "LOAD\n"
"Protocol"))
        self.pushButton_SaveProtocol.setText(_translate("TrainingProtocolWindow", "SAVE\n"
" Protocol"))
