# Copyright 2026 CNR-STIIMA
# SPDX-License-Identifier: Apache-2.0

controller_manager:
  ros__parameters:
    update_rate: 500 # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    state_controller:
      type: ethercat_controllers/CiA402Controller

    ft_sensor_command_broadcaster:
      type: force_torque_sensor_broadcaster/ForceTorqueSensorBroadcaster

    remapping_controller:
      type: "remapping_controller/RemappingController"

ft_sensor_command_broadcaster:
  ros__parameters:
    frame_id: "ee_link"
    interface_names:
      force:
        x: "ft_sensor/force.x"
        y: "ft_sensor/force.y"
        z: "ft_sensor/force.z"
      torque:
        x: "ft_sensor/torque.x"
        y: "ft_sensor/torque.y"
        z: "ft_sensor/torque.z"
    # offset:
    #   force:
    #     x: 249.12
    #     y: -15.15
    #     z: 18.6
    #   torque:
    #     x: 0.12
    #     y: -0.7
    #     z: 2.12  

joint_trajectory_controller:
  ros__parameters:
    joints:
    - joint_z
    - joint_y
    - joint_x

    command_interfaces:
    - position
    - velocity

    state_interfaces:
    - position
    - velocity

    command_joints:
    - remapping_controller/joint_z
    - remapping_controller/joint_y
    - remapping_controller/joint_x

    set_last_command_interface_value_as_state_on_activation: false
    speed_scaling:
      initial_scaling_factor: 1.0
      filter_coefficient: 1.0
      policy: "MINIMUM"
      subscribed_topics:
      - "~/speed_scaling_input"

    constraints:
      goal_time: 0.0 #Infinite time to enter in the goal tolerance
      joint_x:
        trajectory: 0.1
        goal: 0.005
      joint_y:
        trajectory: 0.1
        goal: 0.005
      joint_z:
        trajectory: 0.1
        goal: 0.010

state_controller:
  ros__parameters:
    dofs:
    - joint_x
    - joint_y
    - joint_z

remapping_controller:
  ros__parameters:
    joints:
    - joint_x
    - joint_y
    - joint_z
    input_command_interfaces:
    - position
    - velocity
    output_command_interfaces:
    - position
    - offset_velocity
