# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100 # Hz

    state_controller:
      type: ethercat_controllers/CiA402Controller

    fmrrehab_controller:
      type: "scaled_fjt_controller/ScaledFjtController"

    fmrrehab_admittance_controller:
      type: admittance_controller/AdmittanceController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

state_controller:
  ros__parameters:
    dofs:
    - joint_1
    - joint_2
    - joint_3

fmrrehab_controller:
  ros__parameters:
    joints:
    - joint_1
    - joint_2
    - joint_3
    command_interfaces:
    - position
    - velocity
    state_interfaces:
    - position
    - velocity
    open_loop_control: true
    constraints:
      goal_time: 0.0

fmrrehab_admittance_controller:
  ros__parameters:
    joints:
    - joint_1
    - joint_2
    - joint_3
