cart_coordinates:
- [ 0.0, 0.0, 0.0 ]
- [ -0.5, -1, -0.5 ]
- [ 0.0, 0.0, 0.0 ] #Always end with home position

velocities:
- [ 0.0, 0.0, 0.0 ]
- [ 0.5, 0.5, 0.5 ]
- [ 0.0, 0.0, 0.0 ]

accelerations:
- [ 0.0, 0.0, 0.0 ]
- [ 0.0, 0.0, 0.0 ]
- [ 0.0, 0.0, 0.0 ]

durations:
- 0.0
- 5.0
- 10.0
