name: ros2

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  BUILD_TYPE: Release

## Try to use Docker --- 
jobs:
  build:
    name: Build on ros ${{ matrix.ros_distro }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-24.04]
        include:
        - os: ubuntu-24.04
          ros_distro: 'jazzy'
    container:
      image: ros:${{ matrix.ros_distro }}-ros-base

    steps:   
    - name: Create workspace
      run: mkdir -p src/Fit4Med

    - name: Checkout code
      uses: actions/checkout@v3
      with:
        path: src/Fit4Med

    - name: Setup ROS environment
      run: |
          source /opt/ros/${{ matrix.ros_distro }}/setup.bash
          rosdep update
      shell: bash
    - name: Checkout Fit4Med dependencies (VCS)
      run: |
        source /opt/ros/${{ matrix.ros_distro }}/setup.bash
        vcs import src < src/Fit4Med/.repos
      shell: bash

    - name: Install Dependencies with rosdep
      run: |
        source /opt/ros/${{ matrix.ros_distro }}/setup.bash
        sudo apt-get update
        rosdep install --from-paths src --ignore-src -r -y
      shell: bash

    - name: Check REUSE compliance
      run: |
        pip install reuse
        reuse lint
      shell: bash