name: ros2

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  BUILD_TYPE: Release

## Try to use Docker
jobs:
  build:
    name: Build on ros ${{ matrix.ros_distro }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-24.04]
        include:
        - os: ubuntu-24.04
          ros_distro: 'jazzy'
    container:
      image: ros:${{ matrix.ros_distro }}-ros-base

    steps:   
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup ROS environment
      run: |
          source /opt/ros/${{ matrix.ros_distro }}/setup.bash
          rosdep update

    - name: Checkout Fit4Med dependencies (VCS)
      run: |
        vcs import src < src/Fit4Med/.repos

    - name: Install Dependencies with rosdep
      run: |
        rosdep install --from-paths src --ignore-src -r -y

    - name: colcon build
      run: |
        colcon build --executor sequential --symlink-install --cmake-args -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }}

    - name: colcon test 'plc_controller'
      run: |
        colcon test --packages-select plc_controller --event-handlers console_direct+ --ctest-args --rerun-failed --output-on-failure